### ISSUE TITLE
Auto-create step with new file

### ISSUE THREAD

**Issue by ncspost** [orchest/orchest#1026]
# Describe the problem this improvement solves

When I create a new file, I want to immediately add it to a step, so that there are fewer clicks in my workflow.

# Describe the solution you'd like

- Add a checkbox to the new file form
- Potentially remove new file dialog
- [Figma file](https://www.figma.com/file/BXk97lVzalwYVHvlSU7Y7N/?node-id=1324%3A10738)

# Screenshots

<img width="1895" alt="CleanShot 2022-06-06 at 12 31 40@2x" src="https://user-images.githubusercontent.com/6852479/172152685-8c762f7f-2bb4-4a34-a3da-4379ecca161b.png">

**Comment by ricklamers** [comment]
I think the copy for the checkbox should be "Create a new step for this file"

Also, I think the checkbox can be auto-checked as I believe that's the common case, for when creating the file in the file manager integrated into the pipeline editor.

Files created in JupyterLab (or in VS Code/PyCharm with the SSH workspaces feature coming up, won't have this dialog naturally).
