### ISSUE TITLE
Improve documentation of installation targets

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#1052]
**Describe the problem this improvement solves**
At the moment, we are documenting two different installation methods:
- minikube
- `kubectl`

and, in addition, our convenience script.

However, it would be good to add more clear separation between all these methods, and add other interesting targets such as EKS (see #930, #885).

**Describe the solution you'd like**
A very clear and easy to navigate installation page in which users can pick the method that best suits them.

**Comment by yannickperrenet** [comment]
In https://github.com/orchest/orchest/pull/1048 we introduced an "installation widget" that covers installing: `minikube` or `microk8s` on Linux, Windows or macOS.

We have tested running on GKE and EKS which both worked, so installation steps for those will be added soon :tm:

**Comment by yannickperrenet** [comment]
https://github.com/orchest/orchest/pull/1094 added instructions for GKE and EKS :raised_hands:
