### ISSUE TITLE
Connection line between two steps in the pipeline could not been deleted

### ISSUE THREAD

**Issue by xafdl123github** [orchest/orchest#1057]
Connection line between two steps in the pipeline could not been deleted.

![1](https://user-images.githubusercontent.com/44426610/175477622-7370fc8f-abc8-4119-a737-1d8a4feeca6d.png)

**Comment by astrojuanlu** [comment]
Hello @xafdl123github! You can do it by clicking the line and then pressing the `Del` key on your keyboard:


https://user-images.githubusercontent.com/316517/175481795-8d473678-c09c-46ec-ad29-57907968f21b.mp4

**Comment by xafdl123github** [comment]
Okay. Thank you very much @astrojuanlu

**Comment by yannickperrenet** [comment]
Glad the issue was resolved and don't hesitate to keep asking us questions whenever you bump into something :wink: 

@ncspost Might be something to look into with respect to discoverability.

**Comment by astrojuanlu** [comment]
> @ncspost Might be something to look into with respect to discoverability.

Maybe right-click actions for connectors as well?
