### ISSUE TITLE
JupyterLab doesn't render properly

### ISSUE THREAD

**Issue by iannbing** [orchest/orchest#1075]
**Describe the bug**

JupyterLab has this issue where it doesn't render properly when it's not "visible on screen" during certain phases in its app loading phase. This happens a lot because it is embedded in an iframe.

**Expected behavior**
JupyterLab should expand to the full area.

**To Reproduce**

Switch out the view while it's initializing (i.e. before the starting animation ends). E.g. quickly switch to Pipeline Editor during the animation.

**Screenshots**
![jupyterlab-issue](https://user-images.githubusercontent.com/627607/176762795-546f6a0b-097f-4938-93eb-38a9024a3156.png)

**Comment by yannickperrenet** [comment]
Fixed by https://github.com/orchest/orchest/commit/f2e6087c9e6309f98dbc35432c41290b819cd94b
