### ISSUE TITLE
How about using code-server to edit the .py script?

### ISSUE THREAD

**Issue by howie6879** [orchest/orchest#110]
Great project for me, thx!

I have a little idea in the actual use:
- Jupyterlab works well, but not so well for editing .py scripts, how about using [code-server](https://github.com/cdr/code-server) to edit the .py script?
- Currently, a project has multiple pipelines, scripts under pipelines can be shared, I have a requirement is whether project-A can share some scripts of project-B, or there can be a concept of **public script directory** for any pipelines to use.

Looking forward to your reply.

**Comment by ricklamers** [comment]
Hi @howie6879! Thanks for your recommendations.

For a better experience editing scripts we have actually looked at `code-server`. We’ll take your suggestion as a +1 in our tally which means it’ll get higher priority on our things to do. We still have to iron out details, but we want to make editing your projects as simple as possible.

For sharing code beyond the files in a project we recommend adding them to the environment using language native packages such as a Python package installed through `pip`.

**Comment by howie6879** [comment]
Hi @ricklamers !

Thanks for your reply, I plan to try Orchest in my team.

> For a better experience editing scripts we have actually looked at `code-server`. We’ll take your suggestion as a +1 in our tally which means it’ll get higher priority on our things to do. We still have to iron out details, but we want to make editing your projects as simple as possible.

Continuous attention

> For sharing code beyond the files in a project we recommend adding them to the environment using language native packages such as a Python package installed through `pip`.

Is this approach not friendly enough?

When the team members need to share their scripts, this problem bothers me because the scripts of each project are not shared.

I hope that the team can provide some common scripts to be selected by pipeline

**Comment by ricklamers** [comment]
@howie6879 your comment sparked some more discussion in our team about how we can simplify sharing code between projects. The notion of shared components have been on our mind for a while. 

Would you be up for a quick chat (could be on Slack if you prefer) to better understand your team’s needs for code sharing?

**Comment by howie6879** [comment]
Okay, let's communicate on slack
