### ISSUE TITLE
Orchest-cli: Error: No such option: --socket-path

### ISSUE THREAD

**Issue by Bogehaven** [orchest/orchest#1101]
Getting the error `Error: No such option: --socket-path` when trying to install orchest on a fresh microk8s cluster. 

Tried creating a new conda environment with the same result. orchest-cli version installed is 0.4.1

**Comment by yannickperrenet** [comment]
Hi @Bogehaven we are looking to release `v2022.07.2` later today which will also release the new version of the `orchest-cli` that includes the `--socket-path`. 

But I guess you noticed that yourself as well. Great to see you are looking to try it out already though! :100:
