### ISSUE TITLE
Clear step logs the moment the step is included in another interactive run

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#1105]
**Describe the problem this improvement solves**
Right now it is confusing because it is unclear whether you are looking at logs of a previous run or the current run. Then suddenly all the logs are cleared and thus you know there are the new logs.

**Describe the solution you'd like**
Clear the logs the moment the step is included in a new run. Then when you inspect the logs and none are there, you know you just have to wait for the step to start executing.

**Video**

https://user-images.githubusercontent.com/26223174/178477117-0016751d-df9d-4776-b652-e82ba50e4a3d.mp4

**Comment by fruttasecca** [comment]
Should this happen the moment the interactive run request is made (i.e. synchronously to the API request) or by the celery-worker when the run starts? The former doesn't scale too well with big pipelines but perhaps I'm overestimating, while the latter only clears the logs later, there will be `PENDING` steps that still have logs.

**Comment by yannickperrenet** [comment]
> Should this happen the moment the interactive run request is made (i.e. synchronously to the API request) or by the celery-worker when the run starts?

I would say the former is the ideal situation, but if it doesn't scale well (e.g. a request has to be made for every step to clear its logs) then I think it is fine to go with the latter approach as long the described issue is solved (i.e. no longer confusion of whether you are looking at old logs or logs of the current run -- remember that in the logs view, you don't see the status of a step).

**Comment by fruttasecca** [comment]
>I would say the former is the ideal situation, but if it doesn't scale well (e.g. a request has to be made for every step to clear its logs

I think this can be taken care of transparently by the `orchest_api.py` module of the `orchest-webserver` when relaying the request of an interactive run from the client to the `orchest-api`. When it comes to scaling I was mostly worried about the number of steps and file deletion requests that would need to be synchronously sent during the execution of the endpoint logic (e.g. `os.system`) but I think I was too eager to be worried about that. I'll try to make a PR today about this, it has been lingering for too long imo
