### ISSUE TITLE
Microk8s: Error: No such option: --socket-path

### ISSUE THREAD

**Issue by Bogehaven** [orchest/orchest#1127]
V2022.07.2 is out and the instructions for installing microk8s on a microk8s cluster is updated on the website, but the archest-cli library doesn't seem to be updated to be able to use the socket-path option. After running `pip install --upgrade orchest-cli` the version I have is 0.4.2

**Comment by yannickperrenet** [comment]
(Continuation on issue: https://github.com/orchest/orchest/issues/1101.)

Hi @Bogehaven, I've just created a [virtual environment](https://docs.python.org/3/library/venv.html) and installed the `orchest-cli` using `pip install --upgrade orchest-cli` and when running `orchest install --help` I do see the `--socket-path` option listed.

Are you sure you are actually invoking the newly installed `orchest-cli`? For example, you can check `which orchest` to see the path to the executable. 

To verify that you are indeed using version `0.4.2` could you run `orchest --version` and share the output?

**Comment by yannickperrenet** [comment]
I assume you have managed to resolve the issue and were able to successfully use the `--socket-path` option. Feel free to re-open in case you haven't :innocent:
