### ISSUE TITLE
Expand editor support with integrated code-server

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#113]
This issue keeps track of the integration of the code-server browser based VS Code editor.

As per @howie6879's recommendation we'll look into how and whether it makes sense to expand the available editors beyond JupyterLab.

At the moment VS Code can be used with Orchest by opening the `orchest/userdir/` directory in VS Code directly on the host on which Orchest is installed (or through SSH if it's on a remote server).

**Comment by yannickperrenet** [comment]
With the upcoming services feature, users are able to use the VC Code editor (through code-server) from within Orchest.
