### ISSUE TITLE
`View` option in context menu in file-manager not working correctly

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#1152]
**Describe the bug**
As per title. When right-clicking on a file in the file-manager (to open the context menu) and clicking `View`, the following error comes up (even when it is untrue):

![image](https://user-images.githubusercontent.com/26223174/180797901-cf33af32-e010-4ccd-9b83-07d1f051d30c.png)

**Expected behavior**
Preview a file when pressing `View` in the context menu.

Moreover, why do we even require the file to be assigned to a Pipeline Step in order for it to be "previewable"? I don't see why that should be required.

**To Reproduce**

1. Go to the file-manager in the Pipeline Editor
2. Right click to open the context menu
3. Click `View`

**Comment by ricklamers** [comment]
> I don't see why that should be required.

This is because of the parent/child navigation feature. I’m already working with Nick on a redesign that makes that feature optional enabling previewing all files in the project.

**Comment by ricklamers** [comment]
Worth mentioning this issue also occurs when the view action is triggered by double clicking a file in the file manager when the pipeline editor is in read only mode. See #1191 for a more detailed description.

**Comment by ricklamers** [comment]
Fixed

**Comment by ricklamers** [comment]
Note https://github.com/orchest/orchest/issues/864 is still open, will be shipped soon.
