### ISSUE TITLE
Problem with the Environment building an image

### ISSUE THREAD

**Issue by fx230** [orchest/orchest#1171]
**Describe the bug**
It is not possible to build an Environment.
Restart of Orchest didn't fixed it.
ERROR:   "Starting worker...
                  Starting image build.......There was a problem building the image. The building script had a non 0 exit code, build failed."

**Expected behavior**
Building an Environment image

**To Reproduce**

1. Go to Environment
2. Add python lib with pip install
4. Click on Build
5. Scroll down to logs
6. See error

**Screenshots**
<img width="1410" alt="orchest_error" src="https://user-images.githubusercontent.com/92318399/182806566-9f006005-c77c-4d26-8fd7-f2f2fec9da9b.png">

**Environment**

- OS: Ubuntu 20.04 LTS
- Browser: Safari 15.5
- Orchest's version: v2022.08.1

**Comment by fruttasecca** [comment]
Hi @fx230, thanks for reporting the issue. We are looking into it, is our first priority at the moment.

**Comment by fruttasecca** [comment]
Are you getting the issue only when installing with `pip`?

**Comment by fx230** [comment]
no its also didn't work with the example in the screenshot (mamba) also sudo apt update didn't work

**Comment by fx230** [comment]
Thanks for the quick reply.
It works now, but really slow(20+ min for pip install pycocotools). About 4 weeks ago it was much faster. Is this a problem with my system and the resources I have given to Kubernetes?

**Comment by fruttasecca** [comment]
>It works now, but really slow. About 4 weeks ago it was much faster.

On which version were you previously?

>Is this a problem with my system and the resources I have given to Kubernetes?

Could be. If you are running with minikube, try `minikube start --cpus max --memory max --driver=docker --addons ingress` after deleting the cluster (`minikube delete`).

>When I try to install pycocotools I get an error, other libs work.
Is it possible to install pycocotools?

Every python package should be installable, I suggest to open a separate issue about this.

**Comment by fruttasecca** [comment]
Did this happen on a fresh install or on an update?

**Comment by fx230** [comment]
> On which version were you previously?

I'm not sure, I think it worked perfectly with v2022.05.
It started getting really slow with v2022.07, then error #1171 occurred, I then upgraded to v2022.08.1 and fixed the error with your solution.

>Could be. If you are running with minikube, try minikube start --cpus max --memory max --driver=docker --addons ingress after deleting the cluster (minikube delete).

I started a new cluster with the above settings. It is still very slow, but I suspect that it is not Orchest but the internet connection of my host system.

>Every python package should be installable, I suggest to open a separate issue about this.

I will create a new issue

>Did this happen on a fresh install or on an update?

neither nor error #1171 occurred just like that and pycocotools could not be installed before or after the update

**Comment by fruttasecca** [comment]
>I'm not sure, I think it worked perfectly with v2022.05.

I guess here you mean `v2022.07.5`, `v2022.07.7` (both of these being on k8s, in your case, probably, minikube)? Just making sure. 

>I started a new cluster with the above settings. It is still very slow, but I suspect that it is not Orchest but the internet connection of my host system.

Your internet connection speed can indeed greatly affect the first moments of running Orchest, given that some images are still downloading in the background after installation. If it's super slow always then it might be worth investigating. What do you mean with slow here? Slow env builds? Slow pipeline runs? 

>I will create a new issue
ty :)

**Comment by fx230** [comment]
>Every python package should be installable, I suggest to open a separate issue about this.

Problem solved I forgot to install the build-essential with gcc

>Your internet connection speed can indeed greatly affect the first moments of running Orchest, given that some images are still downloading in the background after installation. If it's super slow always then it might be worth investigating. What do you mean with slow here? Slow env builds? Slow pipeline runs?

It's about the environments. Downloading the packages takes up to 2h(PyTorch 189MB). A maximum download rate of 12.7kB/s is given. When I test downloading a file in Jupyterlab I get a download rate of 32.1 MB/s.
<img width="1410" alt="slow_download_env" src="https://user-images.githubusercontent.com/92318399/182857701-8e4296d5-7501-41ff-8579-0c73bd6c4a22.png">
<img width="1021" alt="fast_download_jupy" src="https://user-images.githubusercontent.com/92318399/182857751-f73ea650-822a-47af-94b8-fe0c1309dddc.png">

**Comment by fruttasecca** [comment]
>Problem solved I forgot to install the build-essential with gcc

great to hear! :)

>It's about the environments. Downloading the packages takes up to 2h(PyTorch 189MB). A maximum download rate of 12.7kB/s is given. When I test downloading a file in Jupyterlab I get a download rate of 32.1 MB/s.

noted, will keep digging

**Comment by fruttasecca** [comment]
Hi @fx230, we aren't able to reproduce the issue, despite witnessing it once. Nevertheless, we are keeping a close eye on this.

**Comment by yannickperrenet** [comment]
(Continuation on https://github.com/orchest/orchest/issues/1171#issuecomment-1204978484.)

In case you are running Orchest on a remote instance that has authentication enabled, you can use the following script to cleanup the builder cache:
```python
import requests

# TODO: Insert information.
INSTANCE_URL = "http://localorchest.io"
INSTANCE_USERNAME = "insert-username"
INSTANCE_PASSWORD = "insert-password"


def main():
    session = requests.Session()
    data = {
        "username": INSTANCE_USERNAME,
        "password": INSTANCE_PASSWORD,
    }
    resp = session.post(
        f"{INSTANCE_URL}/login", timeout=4, data=data, allow_redirects=True
    )
    if resp.status_code != 200:
        raise RuntimeError("Instance login failed.")

    resp = session.post(
        f"{INSTANCE_URL}/catch/api-proxy/api/ctl/cleanup-builder-cache",
        timeout=4,
        allow_redirects=True,
    )
    if resp.status_code != 201:
        raise RuntimeError("Builder cache cleanup failed.")


if __name__ == "__main__":
    main()
```

In most cases this then makes it possible to start building Environments again. Please know that we are actively working on resolved this issue (e.g. in #1198).

**Comment by astrojuanlu** [comment]
I tried the script and it succeeds, but the environment failures persist. This is what I see on k9s:

```
│ main error creating build container: writing blob: adding layer with blob "sha256:4a4852b2e935bcc851606b5d22420779a2efe7b6932c9d6eb8b34ede789fd5c0": error creating layer with  │
│ main Error: exit status 125
```

Latest Orchest version (2022.08.8), Python base image (selected from the UI), empty set-up script. Tested with an empty project.

**Comment by astrojuanlu** [comment]
I confirm that upgrading to 2022.08.10 solved environment build for me, thanks to #1238 (at the cost, as explained there, of making them a tad slower temporarily). Thanks folks 🙏🏽

**Comment by ricklamers** [comment]
We've fixed this using a temporary work-around of not using a builder cache. The issue should not longer occur starting from v2022.08.10 (at a slight performance hit).

We're releasing a change to environment image building soon (ETA 2 weeks) (https://github.com/orchest/orchest/tree/improv/speedup-image-builds) and that will restore good performance.

**Comment by fruttasecca** [comment]
With release [v2022.09.2](https://github.com/orchest/orchest/releases/tag/v2022.09.2) we can consider this closed.
