### ISSUE TITLE
JupyterLab's layout blocks the right file from opening

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#118]
JupyterLab caches its layout, which blocks the right file from opening if JupyterLab wasn't loaded in the iframe already.

**Comment by ricklamers** [comment]
Can we clarify this issue a bit? @yannickperrenet

**Comment by yannickperrenet** [comment]
I would have to guess, since you had already opened this issue in our internal ticketing system. And so I opened the issue here when moving to GitHub's issue tracker.

**Comment by ricklamers** [comment]
This was already fixed when we changed how we open files in JupyterLab (through DocManager).
