### ISSUE TITLE
Notifications when builds and pipelines have finished executing

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#120]
Notifications should be made optional.

Without notifications the user always needs to check the pipeline or build in order to know whether or not it is done building.

Notifications can be browser based (when inside the application) but possible also via integrations such as email or Telegram.

**Comment by yannickperrenet** [comment]
Would be great if we have some form of webhooks. This way users can specify a URL to which we will send the appropriate requests to indicate applications status, e.g. pipeline run failure.

**Comment by yannickperrenet** [comment]
> also via integrations such as email

or Slack! I would really like to see this feature added to be honest :smile:

**Comment by astrojuanlu** [comment]
Also for job failures - I find myself realizing that some runs have failed after a few hours or days.

I think webhooks are the way - folks can then connect that to any system they like.

**Comment by liflovs** [comment]
Upvoting this. Impossible to keep track of failures at the moment, unfortunately.

**Comment by hamisB** [comment]
Upvoting this too. Just found out some runs have failed a few hours ago. This notification feature could be a game changer :)

**Comment by sawtooth9** [comment]
Upvoting this as well, for job failures in particular. It isn't hard to monitor when you only run a few jobs or you are using it for your own purposes. However, we are frequently running into this problem now that we have many jobs run every night, and many people within our organization rely on the data that flows with these job runs.

**Comment by fruttasecca** [comment]
Hi @liflovs @hamisB @sawtooth9, we are going to start working on this in a few days, we are exploring an array of options and collecting preferences and brainstorming a bit. Would webhooks be a strong preference here, or is some kind of jobs dashboard (https://github.com/orchest/orchest/issues/485) more likely to suit your workflow? Solutions aren't exclusive, so feel free to propose.

**Comment by liflovs** [comment]
@fruttasecca dashboard is "nice" to have but webhooks is "must" to have imho, because we need to know sometimes immediately when something fails and react. In some way we can already check on jobs if we want to, but we have to do it proactively

**Comment by sawtooth9** [comment]
@fruttasecca The ideal workflow for us would likely be something similar to what is described in #865 so we could create/add to a report that is alongside all of our other monitoring in the dashboard we use day-to-day. That said, a built-in dashboard or webhook would be extremely helpful as well. Most of our jobs run overnight so the immediacy of the webhook isn't necessary for us, but being able to send out a slack notification when a job fails or collecting the events from a webhook would be a great feature.

**Comment by yannickperrenet** [comment]
For everyone interested in enabling notifications in Orchest (which were introduced in `v2022.06.3`), check out our docs: https://docs.orchest.io/en/stable/fundamentals/notifications.html

![image](https://user-images.githubusercontent.com/26223174/172376145-04934b94-3ae0-4446-8fc5-aa8ca63bcceb.png)
