### ISSUE TITLE
Add installation procedure for AWS Fargate

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#1208]
A user requested adding the installation procedure for AWS Fargate to our docs: https://aws.amazon.com/fargate/

> AWS Fargate is a serverless, pay-as-you-go compute engine that lets you focus on building applications without managing servers. AWS Fargate is compatible [with both Amazon Elastic Container Service](https://aws.amazon.com/ecs/?pg=ln&sec=hiw) (ECS) and [Amazon Elastic Kubernetes Service](https://aws.amazon.com/eks/?pg=ln&sec=hiw) (EKS).

**Comment by ricklamers** [comment]
EKS configured to use Fargate might be able to run Orchest. Although given the limitations as defined in https://docs.aws.amazon.com/eks/latest/userguide/fargate.html there might be some problems.

Currently, it isn't supported and we don't have any plans yet to add support for it. Will close this issue and leave it up for other users with the same question.
