### ISSUE TITLE
Hide 'run incoming steps' button if a step has no incoming steps

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#121]
If a step has no incoming steps, then pressing "run incoming steps" will not execute anything but the orchest-api will still be called. It would be better, if the button is not even shown to the user.

@ricklamers What do you think? We first wanted to add a client side warning, but I felt this is actually out of place since clicking away the warning takes the user more time than executing the "empty" pipeline run.

**Comment by ricklamers** [comment]
I’m not sure if having the button be a no-op is worse than hiding the button.

I have a slight preference for hiding the button I think.

**Comment by yannickperrenet** [comment]
> I have a slight preference for hiding the button I think.

Lets stick with that approach then as I think a no-op button is confusing.

**Comment by ricklamers** [comment]
Fixed in https://github.com/orchest/orchest/commit/507e40db07993cde283bfc2dac7d12ec324f3bbf.
