### ISSUE TITLE
ipywidgets gives `Model not found` errors

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#1235]
**Describe the feature you'd love to have in Orchest**

It would be nice for Orchest to install ipywidgets on Jupyter by default.

**Is your feature request related to a problem? Please describe.**

Initially I was not able to make anything based on ipywidgets work, but then I realized I probably needed to install it globally for Jupyter, and not as part of a particular environment. That turned out to be the solution.

However, I don't think our average user will reach that conclusion so quickly.

**Additional context**

One alternative is just to document this better: for example, by adding a "Error displaying widget: model not found" entry to the FAQ. But both approaches are not mutually exclusive: we can add that entry to the FAQ anyway, and still install ipywidgets by default, which is quite common.

**Comment by yannickperrenet** [comment]
I remember implementing this back in the day, don't the following lines install `ipywidgets` for the user?

https://github.com/orchest/orchest/blob/89d5bdc8b4dd40a0106b9b90bf9c702677b5b445/services/jupyter-server/requirements.in#L4

and 

https://github.com/orchest/orchest/blob/b90c2e12604cac5a407f1ff20b8b3042e094800f/services/base-images/runnable-shared/runner/requirements-user.txt#L2

Sounds also like the approach that you took?

**Comment by astrojuanlu** [comment]
I acknowledge that this procedure follows the official documentation though: https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-in-jupyterlab-3-x

**Comment by astrojuanlu** [comment]
> Confirmed that upgrading `jupyterlab_widgets` on the JupyterLab environment to 3.0 worked.

Mistery solved, PR incoming.

**Comment by astrojuanlu** [comment]
I'm nothing though that this _might_ cause some incompatibilities with ipympl... https://github.com/matplotlib/ipympl/issues/460#issuecomment-1231317821

**Comment by astrojuanlu** [comment]
Repurposed gh-1242 to cap `ipywidgets`, instead of upgrading it. This still solves the issue while giving time for the ecosystem to adapt.
