### ISSUE TITLE
`Invalid response: 413 Request Entity Too Large` when using interactive widgets in Orchest

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#1236]
**Describe the bug**
When using interactive widgets inside Orchest (see #1235) I frequently get errors like these, usually right after creating the first widget:

![image](https://user-images.githubusercontent.com/316517/187021102-f30fe64e-3f39-4d9d-ad97-c79c52fdb73c.png)

"File Save Error for Experiments.ipynb
Invalid response: 413 Request Entity Too Large"

Since autosave is on, this modal dialog will keep popping up even if I dismiss it. The solution is usually to clear the corresponding output.

**Expected behavior**
I can use interactive widgets without errors.

**To Reproduce**

1. Install `ipywidgets` and `ipympl` on Jupyter
2. Create a new project, and install `matplotlib` inside the environment
3. Enable the `ipympl` matplotlib backend by running `%matplotlib ipympl` inside the notebook
4. Make plot with lots of elements
5. Observe error happening

**Screenshots**
![image](https://user-images.githubusercontent.com/316517/187021186-a01ffa33-f486-4c96-8aa7-01bc8859e724.png)

**Environment**

- OS: Linux Mint
- Browser: Firefox
- Orchest's version: 2022.08.8

**Comment by yannickperrenet** [comment]
Just to be absolutely sure, you get this issue only in Orchest? And when running the same code in JupyterLab outside of Orchest this doesn't happen?

**Comment by astrojuanlu** [comment]
Just confirmed that I cannot reproduce this with JupyterLab 3.4.2 outside of Orchest, the save process seems to work normally.

**Comment by yannickperrenet** [comment]
@astrojuanlu Could you verify whether this issue is not fixed by https://github.com/orchest/orchest/pull/1242? Maybe the version upgrade worked its magic? :crossed_fingers:
