### ISSUE TITLE
Pipeline level parameters

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#125]
Ability to define pipeline level parameters, besides the already implemented step parameters.

* Pipeline level parameters to be accessible in all steps. Both the pipeline level and step level parameters will be returned to the user (and so the user has to decide what to do on name collisions).

Implementation details:

* The parameters will be added as `"parameters"` to the pipeline definition.
* When starting a job the pipeline level parameters have to be passed together with the step parameters, but containing a special prefix. Otherwise the selection of pipeline runs in jobs will break.

**Comment by fruttasecca** [comment]
Currently, retrieving (step) parameters is done through `orchest.get_params`, while updating is done through `orchest.update_params`.  Just scanning some alternatives we have:
- have `get_params` return a tuple `(step params, pipeline params)`
- split `get_params` in `get_step_params` and `get_pipeline_params`
- `get_params(pipeline_params=False)`, returns either step or pipeline params based on input

I am leaning towards the first since it's 1 less line of code for the user when retrieving parameters.

About `update_params`: I don't believe we want to allow updating pipeline parameters at run time, since it would be prone to race conditions and encourage bad practices. If we agree on that, `update_params` should be renamed to `update_step_params` (open to suggestions).

**Comment by yannickperrenet** [comment]
> I am leaning towards the first

Agreed. The user can then always choose whether to use only one of them or both.

> If we agree on that, `update_params` should be renamed to `update_step_params`

I agree on the reasoning behind the change as well as the proposed rename.

**Comment by ricklamers** [comment]
I think I might prefer update_step_params and update_pipeline_params.

For consistency I’d prefer to then also have get_step_params() and get_pipeline_params(). With the tuple approach it’s not clear from the method alone which tuple entry is which.

With regard to the updating, I feel like we’re arbitrarily handicapping by now allowing the user to update pipeline params. I can see legit use cases like in the first step determining some global param to be set for all remaining steps in the pipeline. It’s just writing to the JSON file, so it’s something they could do anyway.

Perhaps a warning about race conditions, but that’s possibly implied if the user sees steps running in parallel.

**Comment by yannickperrenet** [comment]
> For consistency I’d prefer to then also have get_step_params() and get_pipeline_params(). With the tuple approach it’s not clear from the method alone which tuple entry is which.

I do not agree with this argument, because when it comes to a function (without checking its docs) you also don't know about the arguments it takes. Similar to the return value, you will have to check. And returning both types of params in one function, I still consider to be a single concern whereas having to call two different functions to get params is overkill.

> It’s just writing to the JSON file, so it’s something they could do anyway.

And exactly for this reason, in my opinion, we should not give the option to the user. Although, a warning could suffice... Don't you think having a warning like: "You should not use this function as it could introduce race conditions", makes the function itself questionable? (On the other hand Celery also lets you do things they don't recommend.)

**Comment by ricklamers** [comment]
Seems to me like having a single function for getting and two separate functions for updating is confusing and asymmetrical.

Either one function for get/set or two functions for get/set.

I don’t think when a function can _potentially_ suffer from race conditions it shouldn’t be created. Take os.makedir as an example :)

**Comment by yannickperrenet** [comment]
> Either one function for get/set or two functions for get/set.

I would vote for one function:

```python
def get_params() -> Tuple[dict, dict]:
  pass

def update_params(step_params: Optional[dict] = None, pipeline_params: Optional[dict] = None) -> None:
  pass
```
