### ISSUE TITLE
orchest-controller UI 404 page not found

### ISSUE THREAD

**Issue by 1270514689** [orchest/orchest#1251]
**Describe the bug**
orchest-controller UI 404 page not found

**Expected behavior**
orchest-controller UI 

**To Reproduce**

1. Installing Orchest using kubectl
2. 
![image](https://user-images.githubusercontent.com/5121903/189074253-f25f9d6d-8696-48ce-95de-49350caca6e9.png)

3. kubectl -n orchest port-forward deployment/orchest-controller 88:80 --address 0.0.0.0
4. curl 127.0.0.1:88   and chrome http://127.0.0.1:88   404 page not found

**Environment**

- OS (e.g. macOS): rocky linux 8.5 k3s 
- Browser (e.g. Chrome): chrome
- Orchest's version (in the settings page):2022.8.11

**Comment by astrojuanlu** [comment]
Hello @1270514689, thanks for opening this issue - does it work if you browse the URL given by `minikube ip`?

**Comment by 1270514689** [comment]
@astrojuanlu thank you. The same issue 404 page not found. I use k3s to creat the app.

**Comment by yannickperrenet** [comment]
Hi @1270514689, if you want to use Orchest you should use the IP returned by following command:
```
kubectl get service orchest-ingress-nginx-controller -n orchest \
      -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
```

the `orchest-controller` doesn't expose any webpage (except for a special `logs` endpoint).

Hope that fixes your issue :)

**Comment by 1270514689** [comment]
@yannickperrenet thank you so much. Because I used the k3s. There are some differents with minikube.
