### ISSUE TITLE
Persisting user configurations of integrated IDEs

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#131]
The configurations of IDEs we integrate in Orchest:

* JupyterLab
* VS Code (through code-server #113)

should be persisted so that a user does not have to configure their IDEs every time. Otherwise (as it is currently), for example added extensions to JupyterLab would have to be reinstalled every time JupyterLab is started.

This feature should be easy to use and so purely defining the configuration programmatically (think dotfiles) is probably not the way to go. Additionally, the configurations should be portable between upgrades of Orchest (and possibly upgrades of the specific IDE service containers).

The current idea is to mount a new directory (from `userdir/.orchest/...`) to the appropriate location in the IDE service container to persist the configurations. For JupyterLab we have to make sure this does not require a rebuild and includes extensions (the `jupyter lab clean` command suggests this approach is possible since it allows for `--extensions`, `--settings` and `--static` flags).

**Comment by yannickperrenet** [comment]
`jupyter lab path` could also be helpful to find the correct target path to mount.

**Comment by ricklamers** [comment]
This as been added 🔥
