### ISSUE TITLE
during orcehst installation "no module named  'orchestcli' " error

### ISSUE THREAD

**Issue by nuhyurduseven** [orchest/orchest#1349]
I am install the oss version in ubuntu via docker desktop. I executed these command sequentially. 
```
pip install --upgrade orcehest-cli
.local/bin/orchest install 
```
and got this error.

Traceback (most recent call last):
  File ".local/bin/orchest", line 5, in <module>
    from orchestcli.cli import cli
ModuleNotFoundError: No module named 'orchestcli'

This is for Orchest latest version and Ubuntu 20.04 docker desktop installation.

**Comment by nuhyurduseven** [comment]
This is my bad, I uninstall orchest package via pip. and run orchest  install again. its done. 
because installed orchest package via pip before.

**Comment by yannickperrenet** [comment]
Hi @nuhyurduseven, you are quick! I was just about to reply :)

Glad to hear you managed to resolve the issue yourself. In case you have any problems in the future, then don't hesitate to open another issue.
