### ISSUE TITLE
Git credentials are not propagated to new kernel terminals

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#1377]
**Describe the bug**
The new "kernel terminals" as opposed to the regular/classic/native terminals (we should come up with some unified terminology here) does not inherit the git credentials configured in the Configure JupyterLab page. As such, the current options are

1. Setting them in every project, or
2. Quitting the kernel terminal and using git from the regular terminal.

I consider this a bug because it's a breaking change with respect to the old default behavior.

**Expected behavior**
As a user, I want to transparently use git with the default terminals so that I don't have to figure out credentials twice or use a distinct terminal for git.

**To Reproduce**

1. Configure git credentials as suggested in https://docs.orchest.io/en/stable/fundamentals/projects.html#using-git-inside-orchest-projects
2. Create a project
4. Go to JupyterLab
5. Open a new Terminal
6. Run `git config --get user.email` and see that nothing comes up :x:
7. Exit the terminal to a regular, non-SSH terminal, rerun `git config --get user.email`, and see the proper value ✔️ 

**Screenshots**
![image](https://user-images.githubusercontent.com/316517/195629006-e9e633ce-fccf-4e18-9eba-e7aa5f4bac1f.png)

**Environment**

- Orchest's version (in the settings page): 2022.10.5

**Comment by yannickperrenet** [comment]
(We are planning to properly tackle this in #483.)

For now, if you want to use git inside Environment shells then, as the name suggests, you need to configure it in the respective Environment (the shell is executes within that Environment).

Does that make sense? 😇

**Comment by astrojuanlu** [comment]
Good to know this is in scope for gh-483 😁 Yes, the workaround is lightweight enough.
