### ISSUE TITLE
"Project not found" warning after rename

### ISSUE THREAD

**Issue by nuhyurduseven** [orchest/orchest#1386]
Hello,

I found a bug in orchest v2022.10.7 version. I renamed a project name and clicked to this name at the project page and I got this warning. Project and session are here, No problem but warning is shown every time. Watch out this point. Pipeline pages is flawless, I don't see any warning while changing between different projects but the project page have a bug after renaming any project name. All projects are accessible. 

![image](https://user-images.githubusercontent.com/44170620/196214483-2641f5a2-80d2-4221-8af9-ca1980352b75.png)

**Comment by ricklamers** [comment]
Thanks for reporting this @nuhyurduseven! We'll investigate

**Comment by yannickperrenet** [comment]
The problem actually happens every time you open a project:

https://user-images.githubusercontent.com/26223174/197493852-faa3c541-8993-4168-9f79-5f2a1be321f0.mp4

**Comment by yannickperrenet** [comment]
Fix will be included in `v2022.10.9`
