### ISSUE TITLE
Creating a new step from scratch is confusing

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#1387]
1. Right click, "Create new step" ✔️
2. Name step ✔️
3. …now what? If the filename is not found, it's unclear how to proceed ❓

https://user-images.githubusercontent.com/316517/196358682-2c2664e4-95d0-4e56-b5ef-2115ee7c96fc.mp4

**Comment by ncspost** [comment]
Part of this is solved by removing the icon from the file path box and only providing validation/feedback through the input field when there is an error...

<img width="661" alt="CleanShot 2022-10-20 at 12 40 08@2x" src="https://user-images.githubusercontent.com/6852479/196938987-78497495-08e2-4b38-96d0-8b5948c234f2.png">

Other things:
- We probably shouldn't let users connect steps unless they have a file path
- The Pipeline step should not say "ready" if the file path is missing... in fact we could probably say "Missing file path"
- Autofill file path from step name may be annoying, vice versa would be useful tho IMO

I think we could probably merge this issue with https://linear.app/orchest/issue/ORC-770/createbrowse-files

**Comment by ricklamers** [comment]
Fixed with https://github.com/orchest/orchest/pull/1401
