### ISSUE TITLE
Login not works on embed

### ISSUE THREAD

**Issue by andersonmfjr** [orchest/orchest#1410]
**Describe the bug**
We own the paid version of Orchest and would like to use the URL inside an <iframe>. The embed works normally, but when logging in the user is always redirected to the same page. The projects page does not open.

**Expected behavior**
When logging in with orchest, even in embed form, I would like the user to be redirected to the projects page.

**To Reproduce**

1. Create HTML simples page and run in localhost
2. Use <iframe> to embed deployed version of orchest, with auth server
3. Login with valid credentials
4. See same page. User is not redirected.

**Environment**

- OS: Ubuntu 22.04.1 LTS
- Browser (e.g. Chrome): Chrome Version 107.0.5304.87 (Official Build) (64-bit)
- Orchest's version (in the settings page): v2022.10.5

**Comment by ricklamers** [comment]
Relevant conversation that ensued: https://community-chat.orchest.io/t/4977127/Hello-guys-I-m-from-Dadosfera-and-I-m-facing-a-problem-when-

**Comment by ricklamers** [comment]
Marked #wontfix for the time being. As mentioned in the public Slack conversation, we currently don't have the bandwidth to add the necessary configurability to make the <iframe> version work. We'd be open to a PR for it though :)!
