### ISSUE TITLE
Orchest install stucks at setting up the Orchest Cluster

### ISSUE THREAD

**Issue by everestas** [orchest/orchest#1413]
**Describe the bug**
I am trying to deploy Orchest.io on AKS. I am running:
`sh
orchest install
`
and it gets stuck at:
```
Installing the Orchest Controller to manage the Orchest Cluster...
Setting up the Orchest Cluster...
🚶 Initializing
```
Logs from orchest-controller:
```
kubectl -n orchest logs -l app.kubernetes.io/name=orchest-controller
E1108 11:55:44.149894       1 controller.go:172] failed to get container runtime version
E1108 11:55:45.150468       1 cluster_controller.go:331] failed to get container runtime version
W1108 11:55:45.150498       1 controller.go:170] dropping Object "orchest/cluster-1" out of the queue: failed to get container runtime version
E1108 11:55:45.150512       1 controller.go:172] failed to get container runtime version
E1108 11:55:46.152360       1 cluster_controller.go:331] failed to get container runtime version
W1108 11:55:46.152391       1 controller.go:170] dropping Object "orchest/cluster-1" out of the queue: failed to get container runtime version
E1108 11:55:46.152405       1 controller.go:172] failed to get container runtime version
E1108 11:55:47.154170       1 cluster_controller.go:331] failed to get container runtime version
W1108 11:55:47.154200       1 controller.go:170] dropping Object "orchest/cluster-1" out of the queue: failed to get container runtime version
E1108 11:55:47.154215       1 controller.go:172] failed to get container runtime version
```

**Expected behavior**
Orchest gets installed.

**To Reproduce**

Run `sh orchest install`

**Environment**

- OS (e.g. macOS): WSL2
- Browser (e.g. Chrome): Edge
- Orchest's version (in the settings page): v2022.11.1

**Comment by yannickperrenet** [comment]
Hi @everestas, thank you for posting the logs of the orchest-controller. At this time we do not support installing Orchest on AKS.  Is using AKS a requirement for you?

In case you are looking to create a PR, the problem seems to be caused by: https://github.com/orchest/orchest/blob/adc0e45239f0bf5f7030313aae989312af6d56b4/services/orchest-controller/pkg/controller/orchestcluster/cluster_utils.go#L411-L426

Not sure though exactly why that fails, since `containerd` (which we support) is used by default on AKS (although not sure you are using it). 

(cc @nhaghighat)

**Comment by everestas** [comment]
Hi, @yannickperrenet, we have everything on set up on Microsoft products, including our k8s cluster. At the moment AKS is a requirement for us. 

Anyway, thanks for your answer!

**Comment by yannickperrenet** [comment]
Totally understandable! Thank you for your response, helps us to prioritize.

**Comment by ricklamers** [comment]
@everestas if you're keen we can plan a session to help you get Orchest up and running on AKS. Although we don't officially support it yet, we should be able to get it to work without much issue. Send me an email at rick@orchest.io and we'll get something scheduled.

It would help you try out Orchest in your desired cloud environment and we'd get some more hands on experience with the AKS peculiarities.
