### ISSUE TITLE
Pipeline_parameters save functionality doesn't work properly in v2022.11.0,

### ISSUE THREAD

**Issue by h-kh** [orchest/orchest#1430]
**Describe the bug**
I change pipeline params and save it, the params are ok when I check them before running any of the steps. But as soon as I run an individual step, the params get back to the previous values. It won't be saved properly until the whole pipeline runs successfully.

**Expected behavior**
It's expected that the params be saved regardless of the steps running successfully or not, 

**To Reproduce**

1. Change pipeline params and save it, 
2. run an individual step(I have two steps)
3. Tnen check the pipeline params, 
4. Check if changes of step 1, is there or not.

**Screenshots**

**Environment**

- OS (e.g. macOS): Windows 10, 
- Browser (e.g. Chrome): Chrome, Firefox
- Orchest's version (in the settings page): 2022.11.0

**Comment by iannbing** [comment]
Thanks for reporting this. It should be fixed in the [latest release 2022.11.4](https://github.com/orchest/orchest/releases/tag/v2022.11.4).
