### ISSUE TITLE
Allow duplication of existing job

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#144]
Enable duplicating an existing job entry. This will make it easier to re-run jobs, especially in the one-off running context.

We will have to take into account whether someone wants to run the same job configuration (e.g. the parameters/environment variable configuration) for the snapshotted version of the job that is being duplicated or the current version of the project.

If the current version is being used we need to reconcile the potential change in parameters/environment variables.

Arguably for re-running a job of the current snapshot we should extend the existing job (thus adding to the pipeline runs that previously ran as part of this job).

**Comment by yannickperrenet** [comment]
When implementing this, I think we should reason about the potential abstractions it would introduce for #200.

**Comment by ricklamers** [comment]
https://github.com/orchest/orchest/pull/433

**Comment by ricklamers** [comment]
> Arguably for re-running a job of the current snapshot we should extend the existing job (thus adding to the pipeline runs that previously ran as part of this job).

For completeness, this was dropped from the first implementation spec.
