### ISSUE TITLE
Make clear that a new job creates a snapshot of the project

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#145]
As of now it's not really clear in the UI that a snapshot of the project is made when a new job is created.

We should find a way to refer to these snapshots such that it becomes more visible to the user that jobs of a single project are based on different versions of the project directory.

For example, we could list a revision number or hash in the job list. As the current implementation of Orchest doesn't require a separate git commit/branch for job snapshots.

**Comment by yannickperrenet** [comment]
Added in: 9db1ad07771998b217e6c57340b092bc00806b8f
