### ISSUE TITLE
💔 Unfortunately, Orchest is no longer actively developing, so can consider a community operation

### ISSUE THREAD

**Issue by dingdayu** [orchest/orchest#1533]
**Describe the problem this improvement solves**
💔 Orchest is no longer actively developing.

**Describe the solution you'd like**
This is an excellent project, although commercialization attempts have failed, can it be turned into community-driven, or donated to open source organizations, such as CNCF or Apache.

Although Apache Airflow is excellent, forgive me for saying that I believe Orches' design philosophy is superior to Airflow.

**Comment by ricklamers** [comment]
To allow the community to extend the project however they see fit we've relicensed to Apache 2.0. Fork, extend and utilize however you see fit!

https://github.com/orchest/orchest/commit/560103a5c7dbdf615a2e0df435076f0ee78b6a1d
