### ISSUE TITLE
Decouple the update process from the git repo

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#167]
Right now we depend on `git pull` during update to make sure the directory structure of the `userdir/` is correct. This should ideally be handled in the code (populated if it doesn't exist, e.g. `os.makedirs`). Right now we pull `master` although this could be out of sync with the release being updated to.

**Comment by yannickperrenet** [comment]
Consequently fixes #166.

**Comment by yannickperrenet** [comment]
For now this is out of scope.

A few notes to keep in mind when working on this in the future:
* At this stage there are two things dependent on the git repo: the `orchest` executable and the `userdir` structure. The `orchest` executable will need to be updated another way if not using the `git pull` mechanism. Additionally, the `orchest` executable should (just like the `orchest-ctl`) be updated before a `orchest update` is invoked, e.g. renaming or adding new containers in new releases.
* Managing the `userdir` structure through code comes with some implications. For example the code then needs to be able to do migrations, which are now handled by git.

**Comment by yannickperrenet** [comment]
For the above reason I will close this issue for now.
