### ISSUE TITLE
Handle build failure for environment build dialog

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#171]
Currently, the build dialog never stops when a build has failed.

![image](https://user-images.githubusercontent.com/1309307/110776824-c3e57c00-8260-11eb-956d-99bd33d8bd5e.png)

The above just hangs indefinitely.

**Comment by yannickperrenet** [comment]
To add to this. If an environment build failed (i.e. its build status is `FAILURE`) the opening the pipeline again will prompt:

![image](https://user-images.githubusercontent.com/26223174/115897410-ad843000-a45c-11eb-80b2-d77f3480707f.png)

Instead it should give an error pop-up saying that one of the environments has failed building. This then also ties in with the indefinite hanging where it should also show this error pop-up if one of the environments has failed building.
