### ISSUE TITLE
Add option to stop all active sessions on JupyterLab image build as a convenience

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#180]
JupyterLab image building is only allowed if there are no active sessions. This prevents dangling images because of JupyterLab instances that are running as part of a session.

The user currently has to manually stop all active sessions to build the JupyterLab image. Which can be cumbersome as we don't provide an aggregate view of all running sessions and/or a way to stop them.

If an option to stop all sessions is added for the user a proper warning should be added clarifying that state of the kernels/memory server as part of the sessions will be lost.

**Comment by yannickperrenet** [comment]
Added in aac0a4c2f508c472f0c4d9da65a0f22de7e0c7ec.
