### ISSUE TITLE
Duplicated logs output

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#190]
The `hello.py` script you see in the screenshot only contains the line `print("hello world")`, but gets duplicated 11 times.

After restarting Orchest this "magic number" became 5.

![Screen Shot 2021-03-21 at 10 41 18 AM](https://user-images.githubusercontent.com/26223174/111975676-26f8cd80-8b01-11eb-96bb-cf89943339b6.png)

Thanks @khaxis for making us aware of this!

**Comment by khaxis** [comment]
Not sure why, but the problem disappeared. Tried a couple of time to restart Orchest, and could not reproduce it.

**Comment by ricklamers** [comment]
Tried to reproduce, but couldn’t. Let’s close it for now, feel free to reopen if you run into it again.
