### ISSUE TITLE
Build system Docker cache invalidated unnecessarily

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#191]
When you create a new branch (`git checkout -b my-new-branch`) after running `scripts/build_container.sh` it will rebuild some images regardless of all files being identical. In particular building `jupyter-server` again takes a long time. This should not happen, Docker should detect that the build context files are unchanged and re-use the existing layers.

**Comment by yannickperrenet** [comment]
This does not happen for me.

Maybe you changed other files that we copy into the Docker build context using the `scripts/build_container.sh` script?

For reference, my installation: `Docker version 20.10.6, build 370c289`.

**Comment by ricklamers** [comment]
Note: This behavior could be different between macOS (running Docker in a VM) and native Linux.

**Comment by yannickperrenet** [comment]
I am not sure what we can do about this. We have been tracking it for quite some time now, so I consider it closed.
