### ISSUE TITLE
Migrate to the new Docker build system

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#192]
Docker has now enabled the new Docker build system (BuildKit) by default. We should explore whether it's now ready for us to use so that we can take advantage of the improvements it brings around caching, performance, and build context flexibility.

More details can be found here:
https://docs.docker.com/develop/develop-images/build_enhancements/

@fruttasecca will take a first jab at this migration.

Note to self: we need proper (cross system) testing. The last time we tried, BuildKit (> 9 months ago) suffered intermittent failures that would appear seemingly randomly.

**Comment by yannickperrenet** [comment]
[Old commit](https://github.com/orchest/orchest/tree/39627b1bcd4460f9059059dbfdb6c6d0926931fb) when we were still using the new Docker build system. At the time we migrated back due to caching issues.

**Comment by ricklamers** [comment]
Update: BuildKit did not give any performance improvements on a full non cached build and is still not enabled by default. Not using it for now.

**Comment by yannickperrenet** [comment]
> Not using it for now.

Will close then. We can always reopen the moment we actually plan to pick up this issue.
