### ISSUE TITLE
Deleting a pipeline file from the project causes the /pipelines page to hang (once)

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#217]
When you delete the pipeline.orchest file of a pipeline in JupyterLab and you navigate to /pipelines the following error occurs:

Endpoint: /async/pipelines/0846896a-c0bd-4a2b-a197-fed47b02ff8b (project uuid)
HTTP 500:
```Error during project pipelines synchronization of 0846896a-c0bd-4a2b-a197-fed47b02ff8b: Orchest-api pipeline creation failed..```

Potentially relevant details:
- There was a session running
- All within the same browser tab
- Reloading the page "makes the error disappear"

**Comment by yannickperrenet** [comment]
I think we need to have a discussion around this issue. Some questions that I have:
* Should only this exact issue of the HTTP 500 status code be fixed?
* What if a user deletes a pipeline through the filesystem? 
* What if a user switches from JupyterLab back to the pipeline? You currently get a blank page.

Questions that are similar but have a slightly different scope:
* What if a user deletes the file of a step while an interactive run is running? Currently, the step for which the file was deleted will fail executing, i.e. `Failure`.
* What if a user deletes a file or pipeline when a snapshot is being created?

---

I think these are all valid questions, but for now out of scope. To a certain degree we expect users to "behave".
