### ISSUE TITLE
Orchest stop occasionally leaves step containers running 

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#239]
Invoking `./orchest stop` while a pipeline run is going on might fail to completely stop all containers, making it so that following the stop command with `./orchest start` will result in failures until the step is done running.

This is most likely a race condition between the start of a step (container) and the collection of containers to stop in `orchest ctl`.

**Comment by yannickperrenet** [comment]
Never ran into this before, but I can definitely imagine it happening.

> This is most likely a race condition between the start of a step (container) and the collection of containers to stop in orchest ctl.

This is probably the case indeed.

**Comment by fruttasecca** [comment]
This has been solved by:
- improving the stop logic in the Orchest CLI, see this [commit](https://github.com/orchest/orchest/pull/241/commits/df47046f89ffdec27d0fad8cd217efacf7fb1c08).
- PR #241 improves the way we handle shutdown in `orchest-api/app/app/__init__.py`, which would also take care of this problem

**Comment by fruttasecca** [comment]
>I am not sure how exactly that solves it. What if the Docker engine were to buffer the container start of a container, then simply running stop twice doesn't solve anything.

This solves the race condition of a step(container) triggering the start of another step without the CLI noticing. I have tried to trigger the case you are mentioning without success. If the Docker engine does indeed buffer it might as well be the case that, assuming we are able to grab containers that are "initializing" (not "running"), the "initializing" containers are buffered as well. It might be that waiting for a short amount of time for the second round of stopping containers in `stop` might cover this without getting us into a rabbit hole.

**Comment by yannickperrenet** [comment]
> It might be that waiting for a short amount of time for the second round of stopping containers in stop might cover this without getting us into a rabbit hole.

I did not mean to solve the case for the full 100%, I just wanted to point out that the Docker engine basically controls whether or not the fix works. Don't think it makes sense to spend time investigating. Regarding "waiting for a short amount of time for the second round", might not be a bad idea; 0.5s?

**Comment by fruttasecca** [comment]
>Don't think it makes sense to spend time investigating.

agree

>Regarding "waiting for a short amount of time for the second round", might not be a bad idea; 0.5s?
I would make it 2 but have no strong feeling about it :)
