### ISSUE TITLE
Session in incorrect state after JupyterLab build

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#243]
### To reproduce

1. Open a pipeline to start a session
2. Go to the global settings to configure JupyterLab
3. Press "BUILD"

Note: The pop-up incorrectly shows twice and the build is actually never triggered.

4. Navigate back to the pipeline editor.

Note: It indicates that the session is still running. However, running `docker ps` shows that the session's containers were successfully stopped by the build action.

### What should happen

* The pop-up with warning should only show once
* The JupyterLab build should have been triggered
* The session status indicator in the pipeline editor should correctly represent the state of the session.

**Comment by joe-bell** [comment]
Fixed by https://github.com/orchest/orchest/pull/245
