### ISSUE TITLE
Migrate React Class Components to Functional Components

### ISSUE THREAD

**Issue by joe-bell** [orchest/orchest#259]
A lot of the workarounds we're doing with SWR and global state are a consequence of using class components.

We can't use hooks or consume more than one context at a time. 

To allows us to move forwards without workarounds, we should consider **incrementally** (not one big refactor) migrating all our existing class components (that depend on external state) to functional components

In the meantime, any new components should be written as Functional Components

**Comment by yannickperrenet** [comment]
@ricklamers This can be closed right?

**Comment by ricklamers** [comment]
Yes 👍
