### ISSUE TITLE
Pipeline step multiple deletes issue multile warning/alerts

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#270]
**Describe the bug**  
Repeatedly pressing the delete button with a pipeline step selected will create an alert every time the delete button is selected.

**To Reproduce**  
Steps to reproduce the behaviour:

1. Go to the pipeline editor
2. Select a pipeline step
3. Select the logs tab, so that the delete button will act on the step and not on the step title/name
3. Press delete multiple times
4. Multiple alerts will pop up, the background will get increasingly darker

**Expected behaviour**  
Pressing a delete when a delete alert already exists should not lead to more alerts getting created. Optionally, the delete button could act as a confirmation.

**Screenshots**  

![image](https://user-images.githubusercontent.com/19429509/119501874-942b1800-bd69-11eb-9fdc-7af3d0bf384f.png)

**Comment by yannickperrenet** [comment]
Can reproduce as well.
