### ISSUE TITLE
Scheduled jobs are scheduled to run at the wrong time

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#273]
**Describe the bug**  
Scheduled jobs are scheduled at the wrong time, to be exact (in my case) they are scheduled to run 2 hours later than defined -- I am in UTC+2.

Could be applicable to cron jobs as well. Did not test this.

**To Reproduce**  

1. Create a new "Scheduled" job
2. Note the time at which you schedule the job
3. Run the job
4. Open the job

Note: the "Scheduled to run" time is off by the number of hours the user's timezone is different from UTC. In my case, I scheduled the job to run at `5:35 PM` and inspecting the job shows "Scheduled to run" to be `7:35 PM`. (I am in UTC+2.)

**Expected behavior**  
The job should run at the defined scheduled time.

**Comment by yannickperrenet** [comment]
I think [this code](https://github.com/orchest/orchest/blob/master/services/orchest-webserver/client/src/components/DateTimeInput.jsx#L26) causes the issue (note the `+ "Z"`):
```js
  getISOString() {
    return parseISO(
      this.state.dateValue + " " + this.state.timeValue + "Z"
    ).toISOString();
  }
```

The backend expects to be receiving UTC datetime strings, but the date entered by the user is actually not adjusted to the timezone of the user.

@ricklamers

**Comment by yannickperrenet** [comment]
This happens for cron jobs as well.

To reproduce:
1. Create a cron job with schedule `* 17 * * *`
2. Run the job
3. Open the job again through the job list view

Note that it states: "Scheduled to run" `May 31, 2021 7:00 PM`. Which also has this timezone issue.

**Comment by yannickperrenet** [comment]
For cron jobs, the current implementation might actually be the correct way. Consider the following:

* The cron string does not contain any timezone information. Should the cron string be modified based on the timezone of the user's client, e.g. user X is in UTC and schedules at `* 17 * * *` and user Y is in UTC+2; should user Y see `* 17 * * *` or `* 19 * * *`?
* Team members might be in different timezones, how do they communicate the schedule of a job? Do they all refer to their local timezone or to the UTC standard in the team?

**Comment by ricklamers** [comment]
I think we decided the cron strings would be entered in UTC.

The JS code you linked seems correct to me. The dates entered by the user (scheduled to run at or cron jobs) are in UTC.

So I think the implementation should:
- Show all dates in user local time
- Get all server dates in UTC
- Enter all dates in UTC

**Comment by fruttasecca** [comment]
>The cron string does not contain any timezone information. Should the cron string be modified based on the timezone of the user's client

As far as I remember this was discussed when implementing cron jobs and we agreed upon the fact that cronjobs would respect UTC. I actually thought we explicitly communicated that at the GUI level, but this does not seem to be the case.

**Comment by yannickperrenet** [comment]
> As far as I remember this was discussed when implementing cron jobs and we agreed upon the fact that cronjobs would respect UTC.

I will add a message indicating that cron strings are to be entered in UTC.

**Comment by ricklamers** [comment]
As per discussion the scheduled time should be entered in local (we should state this as well).

**Comment by yannickperrenet** [comment]
> As per discussion the scheduled time should be entered in local (we should state this as well).

@ricklamers I requested your review on the PR that fixes this. Probably better to reply there.

Scheduled time is now to be entered in local time. However, I don't agree that this should be stated. The application should speak for itself so whenever something is straight forward (like expecting to enter times based on local time) then I don't think it makes sense to be overly explicit.
