### ISSUE TITLE
General Typography Improvements

### ISSUE THREAD

**Issue by joe-bell** [orchest/orchest#278]
**Describe the solution you'd like**  

In https://github.com/orchest/orchest/pull/269#issuecomment-849726325, @ricklamers highlighted that the `Alert` text size is bigger than the rest of the table and feels jarring – we should either:

1. Consider overhauling the typography as a whole to feel more cohesive to the new body size set by Stitches
2. Set a smaller `Alert` variant

**Describe alternatives you've considered**  
N/A

**Additional context**  
N/A

**Comment by yannickperrenet** [comment]
I think this issue is a bit too general and we will be addressing the UI/UX of the application view by view and so I am pretty sure this issue will automagically be solved.
