### ISSUE TITLE
Plasma socket mounting is broken on macOS

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#29]
https://github.com/docker/for-mac/issues/483

**Comment by yannickperrenet** [comment]
According to the official Docker documentation: "Socket files and named pipes only transmit between containers and between macOS processes -- no transmission across the hypervisor is supported, yet."

See: https://docs.docker.com/docker-for-mac/osxfs/#file-types

**Comment by yannickperrenet** [comment]
Should be fixed in https://github.com/orchest/orchest/pull/34

Workaround is to use docker volumes so that the docker containers can communicate over the socket without crossing the hypervisor boundary.
