### ISSUE TITLE
Entering a step title in the properties pane overwrites the file name

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#298]
**Describe the bug**  
When entering a step title in the properties pane of a step, the file name gets prefilled. This means that if a user has already entered a filename it will get overwritten.

**To Reproduce**  
1. Open the pipeline editor
2. Add a new step
3. Enter a file path (just create a new file with the "+ New file"
4. Enter a title

Note that when typing the title, it overwrites the file path. So now the just created file has to be chosen again.

**Expected behavior**  
When typing the title of the step, it should only prefill the file path if the file path is not yet specified.

**Comment by ricklamers** [comment]
Fixed in https://github.com/orchest/orchest/pull/224
