### ISSUE TITLE
Pipeline step run duration indicator

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#303]
**Describe the solution you'd like**  
The current implementation shows the execution time in seconds. This is inconvenient when a step takes a long time (>> 60 seconds).

![image](https://user-images.githubusercontent.com/1309307/121217114-d2542b80-c881-11eb-874d-40855e92893a.png)

**What does your solution aim to solve?**  
Proposal: when the execution time exceeds a minute, show compact hour:minute:second notation instead.

`00:05:33`

**Describe alternatives you've considered**  
Human readable descriptions like: "a little over a minute" feel too imprecise.

A viable alternative could be to always use the compact time indicator, instead of switching to this case after execution exceeds 60 seconds.

**Comment by yannickperrenet** [comment]
I do very much like the idea!

> show compact hour:minute:second notation

How about going with something like: `1hour 3min 15s`?

> A viable alternative could be to always use the compact time indicator, instead of switching to this case after execution exceeds 60 seconds.

I do like always going with the same format, although with the proposed compact format the leading `00:` and potentially `00:00:` would be a waste of space.
