### ISSUE TITLE
Web server is blocked when taking snapshots

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#304]
**To Reproduce**  
Steps to reproduce the behaviour:

- have a project of large size, `head -c 10GB /dev/zero > data`
- create a job
- the webserver will be blocked while the snapshot is being copied

This happens for job and project deletion as well.

**Expected behaviour**  
The web server should not be blocked, i.e. other requests should happen concurrently.

**Comment by ricklamers** [comment]
Nice find!
