### ISSUE TITLE
Job Duplication

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#313]
Creating a job might require setting a lot of variables, parameters, etc. Upon job creation, a snapshot is taken. This means that running the same set of parameters, variables etc. with the latest version of the code requires configuring the job from scratch.

**Describe the solution you'd like**  
One quick job duplication.

**What does your solution aim to solve?**  
Running the same job (given the configuration) but using updated code.

**Comment by yannickperrenet** [comment]
Duplicate of #144?

**Comment by fruttasecca** [comment]
Yep, will close.
