### ISSUE TITLE
Add an "Onboarding Dialog"

### ISSUE THREAD

**Issue by joe-bell** [orchest/orchest#325]
**Is your feature request related to a problem? Please describe.**  
For first-time users, Orchest can be quite overwhelming - with no indication of how to leverage the product's full capabilities (even from a high-level)

**Describe the solution you'd like**  

For first-time users, show an "Onboarding Dialog" with slides that go over Orchest's key concepts/features. It should be short, simple, and enaging.

We could determine whether or not the user is a first-time user via local storage.

**Describe alternatives you've considered**  
N/A

**Additional context**  

Designs shared in private Figma team.

**Comment by ricklamers** [comment]
Closed by #324
