### ISSUE TITLE
Environment images are not available for job runs after update

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#326]
**Describe the bug**  
Environment images are not available for job runs after update

**To Reproduce**  

1. Create a cron job
2. Update Orchest
3. Environment image is deleted
4. Build is not triggered for environments referenced in cron jobs
5. When a job triggers a pipeline run, the run fails because no environment image is available

**Expected behavior**  
The job should succeed in running after an update.

**Environment**

- OS: Linux server
- Browser: Chrome
- Version: 2021.06.1
- Environment: prod, cloud.

**Comment by yannickperrenet** [comment]
Depending on how we approach this issue, it is probably good to be aware of #310.
