### ISSUE TITLE
Adding a button to the pipeline editor to (re)run the entire pipeline

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#327]
**Describe the solution you'd like**  
A one-click button in the pipeline editor to (re)run the entire pipeline. 

Alternatively, the selection of a pipeline run gets lost after changing things in the editor. As of now, you need to reselect the same subset of steps, what if we just had a button that allows you to rerun the previous ran pipeline selection?

**What does your solution aim to solve?**  
Currently, I often find myself selecting the entire pipeline. Would be great if this could be done with a single button. 

**Additional context**  
The most common flows should also have the best UX.

**Comment by ricklamers** [comment]
#428 mentions that a shortcut for this behavior would be nice. That could be more feasible than a dedicated button as adding more and more buttons clutters the UI.

**Comment by yannickperrenet** [comment]
I agree that additional buttons can clutter the UI. However, a shortcut is probably too hidden for users to find out unless we add something else to point them towards the possible shortcuts. This would also solve the fact that some users can't seem to find the dragging functionality.
