### ISSUE TITLE
orchest-webserver start failed: " KeyError: 'ORCHEST_PORT' "

### ISSUE THREAD

**Issue by jjdblast** [orchest/orchest#329]
**Describe the bug**  

I'm trying to install the Orchest on Ubuntu 20.04 LTS ( docker version 18.09.5, docker-compose version 1.27.4 ), after I installed the Orchest and start, I found that orchest-webserver container exited and can not be started.

**To Reproduce**  

1.  git clone https://github.com/orchest/orchest.git && cd orchest
2.  ./orchest install
3.  ./orchest start
4.  docker ps -a 
 
And then you can find the orchest-webserver container shows "Exited (3) XX minutes ago".

I also use `docker logs orchest-webserver` to check the container, which shows that the error is :

 File "/orchest/services/orchest-webserver/app/app/config.py", line 78, in Config
 KeyError: 'ORCHEST_PORT'

**Expected behavior**  
orchest-webserver can be start normally.

**Screenshots**  
![image](https://user-images.githubusercontent.com/3394810/122674405-9cab2d00-d207-11eb-853f-96f85a84ca83.png)

**Environment**

- OS: Ubuntu 20.04 LTS 
- Version: docker version 18.09.5, docker-compose version 1.27.4
- Logs: [what do you see after running `./orchest status --ext`?]
  ```sh
  # Result
  Usage: orchest status [OPTIONS]
  Try 'orchest status --help' for help.

  Error: no such option: --ext
  ```

**Additional context**

**Comment by ricklamers** [comment]
@jjdblast thanks for reporting. It looks like there might be some old container images on your system. Can you run `./orchest update` to make sure all images are up to date?

After the update `./orchest version —ext` should show all images on version 2021.06.3.

**Comment by jjdblast** [comment]
Thanks! The orchest version I'm using is v0.4.1, seems way behind the latest version, after I update and restart orchest, everything works fine!
