### ISSUE TITLE
Upgrade to React v17

### ISSUE THREAD

**Issue by joe-bell** [orchest/orchest#331]
**Describe the solution you'd like**  

We should be on the latest React version

**What does your solution aim to solve?**  

Keeping up to date with the latest version of React will help us to ensure shared libraries (such as `@orchest/design-system` can be tested thoroughly without needing to worry about older versions of React). It'll also help us to avoid any upcoming tech debt

**Describe alternatives you've considered**  
N/A

**Additional context**  
Could be related to #275, but unsure

**Comment by yannickperrenet** [comment]
No need to fix this right now.
