### ISSUE TITLE
Project dropdown doesn't change entity list

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#334]
**Describe the bug**  
Project dropdown doesn't change entity list

**To Reproduce**  

1. Go to jobs
2. Change the project in the dropdown
3. Observe the jobs list not updating, expectation: see jobs of selected project.

**Environment**
- OS: Windows (Orchest runs on Ubuntu Linux)
- Browser: Chrome
- Version: 2021.06.3
- Environment: prod, cloud

**Comment by joe-bell** [comment]
Was this behaviour there previously? I can't seem to find anything related to this behaviour in the history https://github.com/orchest/orchest/commits/master/services/orchest-webserver/client/src/components/JobList.jsx

**Comment by joe-bell** [comment]
Fixed by #338
