### ISSUE TITLE
Ship production JS with sourcemaps

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#339]
**Describe the solution you'd like**  
Ship production JS with sourcemaps

**What does your solution aim to solve?**  
Make it easier to debug errors when not running Orchest with the --dev flag

**Implementation**
We should implement this by changing our frontend compiler configuration. This should be combined with migrating the compilation chain to use `esbuild` #340.

**Comment by yannickperrenet** [comment]
@iannbing @ricklamers Is this something that can now easily be picked up given that we are already using `esbuild` these days?

**Comment by iannbing** [comment]
Yes, it's just a flag in the esbuild build script. However, bundling sourcemaps in a production build is quite uncommon. I think this should be an opt-in option behind a feature flag.

**Comment by yannickperrenet** [comment]
> I think this should be an opt-in option behind a feature flag.

@ricklamers What do you think given that you explicitly mentioned wanting to "ship production JS with sourcemaps"?

**Comment by ricklamers** [comment]
We now to this :)
