### ISSUE TITLE
Pipeline parameters aren't saving when changed

### ISSUE THREAD

**Issue by joe-bell** [orchest/orchest#362]
**Describe the bug**  
In Pipeline settings, parameter JSON isn't saved (only in the client-side/local state)

**To Reproduce**  

1. Go to any pipeline
2. Click on "settings"
3. Scroll down to "Pipeline Parameters"
4. Make change
5. Hit "Save"
6. Refresh

**Expected behavior**  

Parameters should save when changed.

**Screenshots**  
N/A

**Environment**

- OS: [e.g. macOS]
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Environment: [e.g. development, production, cloud]
- Logs: [what do you see after running `./orchest status --ext`?]
  ```sh
  # Result
  ```

**Additional context**  
Fix coming shortly.

**Comment by ricklamers** [comment]
Good find 👍🏻
