### ISSUE TITLE
Environment without should have a clearer build status

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#367]
Minor gui issue:
- create an environment
- save it
- get back to the environments view

The environment has no "build status" since it has never been built.
![image](https://user-images.githubusercontent.com/19429509/124080710-f652f900-da4a-11eb-8c95-98669aabfcea.png)

**Proposed solution**
Have an entry to default to when an environment has never been built, i.e. there is no build status to show, perhaps a `-`?

**Additional context**  
An environment is defined as a base image and a script that will run when the environment image is built. Some other metadata like the environment name is part of the definition. An environment can be built multiple times, for example, to create a new up to date image which reflects the latest base image and/or the modified provided script.  
Each time an environment build is triggered it results in an "environment build" entry, which reflects into the `environments` view. If an environment has never been built no "environment build" entry is there, thus no status is available.

**Comment by joe-bell** [comment]
What about a status of `UNBUILT` 🤔
