### ISSUE TITLE
Improve docs on Orchest CLI

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#371]
**Describe the solution you'd like**  
We lack a page that describes the CLI in depth. Relying on just `orchest help` doesn't seem sufficient/welcoming to new users.

**What does your solution aim to solve?**  
In particular, non obvious commands like the `orchest run|update|install|debug` commands warrant some documentation.

**Comment by yannickperrenet** [comment]
Probably good as a reference: https://docs.docker.com/engine/reference/commandline/cli/.

**Comment by yannickperrenet** [comment]
@ricklamers Given that Orchest is not a CLI application and is primarily used through its UI, do you still think that such an explanation is required?

**Comment by ricklamers** [comment]
I agree it's primary not a CLI application but I think all behaviors that we ship with the CLI  should still be included in the docs (we do of course have _a CLI_, albeit just to manage the Orchest instance).

**Comment by yannickperrenet** [comment]
I added a section to the docs on the [`improv/docs`](https://github.com/orchest/orchest/tree/improv/docs) branch. However, I have kept it to a minimal since I don't think this falls in the 80/20 use cases.
