### ISSUE TITLE
Environment variable names containing spaces are not handled correctly.

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#376]
**To Reproduce**  
Steps to reproduce the behaviour:

1. Create a project or pipeline environment variable with a name containing spaces, e.g. `  a   `, or  `hello world`
2. Start a session
3. Said variables will not be set, i.e. they won't exist in the environment

This is likely affecting the value of said environment variables as well.
Edit: this is only affect the **name** of environment variables.

**Expected behavior**  
Said environment variables should be set in the environment. Assuming that we want to allow such environment variable names.

**Comment by yannickperrenet** [comment]
> Assuming that we want to allow such environment variable names.

I don't think we do. I wouldn't know how to create such a variable, nor how to get its value.

And from [stackoverflow](https://stackoverflow.com/a/2821183/14839751):
> So while the names may be valid, your shell might not support anything besides letters, numbers, and underscores.

I do think we can validate env names when entered through the UI, e.g. conforming with the regex `[a-zA-Z_]+[a-zA-Z0-9_]*`. @joe-bell Thoughts?

**Comment by fruttasecca** [comment]
I must highlight that such a thing is currently possible in docker, e.g. `docker run --rm -it -e " A "=1 python:3.7 python`. I agree that it is confusing and is likely to break depending on the base image so I would be in favour of not allowing it. The check should be both at the client and backend level.
