### ISSUE TITLE
Web update 2021.06.1 -> 2021.07.3 failed to restart

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#397]
**Describe the bug**  
Web update 2021.06.1 -> 2021.07.3 failed to restart

**To Reproduce**  

1. Have 2021.06.1
2. Try to update to 2021.07.3 using the web updater
3. Orchest doesn't restart

**Expected behavior**  
After updating it should auto restart

**Comment by yannickperrenet** [comment]
I remember running into an issue with the web updater as well (about a week ago so the it was more or less about the same versions). However I was not able to reproduce a second time on another Orchest installation.

Just some context, not sure it helps...

**Comment by fruttasecca** [comment]
A debug dump or a part of it could help in identifying the cause.

**Comment by ricklamers** [comment]
Some additional bit of information. After updating through the web updater Orchest is fully shut down (no containers running). And running `./orchest version --ext` showed all images on 2021.07.3. It just hadn't started.

Starting it manually (`./orchest start --port 80 --cloud`) worked without any issue.
