### ISSUE TITLE
Make it possible to abort an individual non-interactive pipeline run that's part of a job

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#398]
**Is your feature request related to a problem? Please describe.**  
When you want to abort a pipeline run (because you observe it failing for example) without botching the whole job a more granular way to stop a single pipeline run of the job (especially if the job is a cron job) is desirable.

**Describe the solution you'd like**  
Make it possible to abort an individual non-interactive pipeline run that's part of a job.

**Describe alternatives you've considered**  
Manually stopping the job and recreating it from scratch. But this has a number of disadvantages, it's cumbersome, error prone, and loses out on the existing pipeline runs in the job. It also automatically uses the latest (different) version of the code.

**Comment by yannickperrenet** [comment]
Has been added:
![image](https://user-images.githubusercontent.com/26223174/153363534-a8d77ca7-1eb2-4f91-80ff-a76e053b7933.png)

Together with an improvement for discoverability in #703.
