### ISSUE TITLE
Failure in update leaves inconsistent services versions

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#401]
**Describe the bug**  
The first step of updating orchest, be it in `web` mode or through the CLI, updates `orchest-ctl` by pulling the latest image. After that, all other services are updated. In the case of an error during the update process, the user might be left with a version of `orchest-ctl` that is not compatible with the other services. 

**To Reproduce**  

- have unstashed changes in the orchest repository
- run an update
- `orchest-ctl` will be updated to the latest version
- the update logic will refuse to continue because there are unstashed changes
- The version of `orchest-ctl` is different and possibly incompatible with the other services.

**Expected behavior**  
In case of an `update` failure (the versions of) services should remain consistent, at least when it comes to the updating process intentionally refusing to continue.

**Comment by yannickperrenet** [comment]
After introducing our own operator (#916) the update process is now completely handled by the `orchest-controller` which will retry until all Orchest services (e.g. `orchest-api`) are on the same version.
