### ISSUE TITLE
./orchest install for the first time takes a long time pulling the docker image from the docker repository.

### ISSUE THREAD

**Issue by dkmahakur** [orchest/orchest#408]
Please find the attached image i have marked the certain image that's creating quite a bit of delay ,like nearly 9-10 minutes,If this was intended please do mention about it in the README.md
![Screenshot 2021-08-03 at 10 13 27](https://user-images.githubusercontent.com/10935989/127982103-97eae439-ddd4-4d2d-b529-09eee4249250.png)

**Comment by ricklamers** [comment]
Hi @dkmahakur. The image pull of the `orchest/orchest-ctl` image shouldn't take that much time. Thanks for pointing it out. It might be a (temporary) issue with [Docker Hub](https://hub.docker.com/u/orchest).

**Comment by ricklamers** [comment]
Let me know if the issue persists.

**Comment by dkmahakur** [comment]
Yeah just realized docker hub is horribly slow since 400hrs CET today .
