### ISSUE TITLE
Indicate update possibility due to new Orchest release in the UI

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#414]
**Example solution**  
A dialog indicating a new version.

![image](https://user-images.githubusercontent.com/26223174/128699819-4442527a-b99f-439a-9ee4-2669436a6ac7.png)

**What does your solution aim to solve?**  
It is beneficial for users to be on the latest version of Orchest. Currently, users need to check themselves whether Orchest has released a new version. In addition updating can also be a hidden feature to some.

**Comment by ricklamers** [comment]
Love this idea ❤️

**Comment by ricklamers** [comment]
(Nitckpick: button spacing)

**Comment by yannickperrenet** [comment]
> (Nitpick: button spacing)

Yes that should definitely be improved

**Comment by yannickperrenet** [comment]
Whoops I miss clicked and accidentally closed the issue. My bad.
