### ISSUE TITLE
H key is captured when typing in the pipeline editor

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#418]
**Describe the bug**  
H key is captured when typing in the pipeline editor

**To Reproduce**  

1. Go to the pipeline editor
2. Click on a step and edit the title in the properties pane
3. Try to type 'H'

**Expected behavior**  
Keyboard input should be captured in the input form

**Environment**

- OS: Linux
- Browser: Chrome
- Version: 2021.08.3
- Environment: production, cloud

**Comment by yannickperrenet** [comment]
What happens if you do:
1. Go to the pipeline editor
2. Click on a step and edit the title in the properties pane
3. Try to type 'H'
4. Refresh page
5. Click on a step and try to type 'H' in the title again
