### ISSUE TITLE
Pipeline `automatic memory eviction` UI hint

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#420]
**Describe the solution you'd like**  
The `automatic memory eviction` pipeline setting could make use of a hint to better explain what's the role of said setting. Services settings already make use of such a construct.

![image](https://user-images.githubusercontent.com/19429509/129696812-b8e32be3-680e-4e88-aa77-423efbff082a.png)

![eviction](https://user-images.githubusercontent.com/19429509/129696613-6ff765ba-2811-4c42-9aff-b42dead931b3.png)

**Comment by yannickperrenet** [comment]
I do really like adding hints in the UI instead of expecting the user to search the docs. Especially since it is a GUI and not code.
