### ISSUE TITLE
Installing ipykernel with pip breaks the Orchest notebook runner

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#425]
**Describe the bug**  
Modifying the pip/conda environment breaks the Orchest notebook runner

**To Reproduce**  

1. Create a project
2. Create an environment that modifies the pip/conda packages in a way that break the dependencies of the notebook runner (which depends on e.g. nbconvert).
3. Try to run a pipeline step with a notebook
4. See failure (no logs in the UI, but in the Celery worker the notebook runner script shows a dependency related error)

**Expected behavior**  
Users modifying their dependencies shouldn't affect

**Environment**

- OS: linux
- Browser: chrome
- Version: 2021.08.3
- Environment: production
- Logs: (example dependency related failure)
```
Traceback (most recent call last):
  File "run.py", line 73, in <module>
    main()
  File "run.py", line 50, in main
    nr.run(file_path)
  File "/orchest/services/base-images/runnable-shared/runner/runner/runners.py", line 116, in run
    ep.preprocess(nb, {"metadata": {"path": self.working_dir}})
  File "/orchest/services/base-images/runnable-shared/runner/runner/preprocessors.py", line 95, in preprocess
    super().preprocess(nb, resources, km)
  File "/opt/conda/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 80, in preprocess
    with self.setup_kernel():
  File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 457, in setup_kernel
    self.start_new_kernel_client()
  File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 428, in async_start_new_kernel_client
    await ensure_async(self.kc.wait_for_ready(timeout=self.startup_timeout))
  File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 89, in ensure_async
    result = await obj
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/asynchronous/client.py", line 131, in wait_for_ready
    msg = await self.shell_channel.get_msg(timeout=1)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/asynchronous/channels.py", line 43, in get_msg
    ready = await self.socket.poll(timeout)
  File "/opt/conda/lib/python3.7/site-packages/zmq/_future.py", line 306, in poll
    f = p.poll(timeout)
  File "/opt/conda/lib/python3.7/site-packages/zmq/_future.py", line 93, in poll
    socket._add_recv_event('poll', future=watcher)
  File "/opt/conda/lib/python3.7/site-packages/zmq/_future.py", line 405, in _add_recv_event
    self._add_io_state(POLLIN)
  File "/opt/conda/lib/python3.7/site-packages/zmq/_future.py", line 575, in _add_io_state
    self._update_handler(self._state)
  File "/opt/conda/lib/python3.7/site-packages/zmq/_future.py", line 591, in _update_handler
    self._get_loop()
  File "/opt/conda/lib/python3.7/site-packages/zmq/_future.py", line 38, in _get_loop
    self._init_io_state(self._current_loop)
TypeError: _init_io_state() takes 1 positional argument but 2 were given
```

**Comment by yannickperrenet** [comment]
This issue sounds very similar to #205 to me. 

@fruttasecca Already looked at numerous alternatives to solve the issue of users wanting to install the same packages we depend on internally. They were somewhat cumbersome so we choose not to implement any of them at that time, maybe it is time to revisit that decision.

**Comment by yannickperrenet** [comment]
Whilst solving this issue, we need to keep in mind that users should be able to bring their own custom image: #438.

**Comment by astrojuanlu** [comment]
This is still an issue, and one that comes up frequently. The root cause seems to be ipykernel:

```
#!/bin/bash

pip install "ipykernel==6.12.1"
```

The setup script above will break interactive pipeline runs and jobs.

At the very least, we should document this somewhere. I see we have a troubleshooting page for development https://docs.orchest.io/en/latest/development/troubleshooting.html but not for users, we could call it FAQ too.

I'll investigate if there are any mechanisms we can use to lock `ipykernel`.

**Comment by yannickperrenet** [comment]
Does that issue exist in the current version of Orchest? Running on the Cloud get's you version `v2022.03.6`, so might be good to check whether it holds in both cases.

**Comment by astrojuanlu** [comment]
I could reproduce the error in `v2022.06.2` with the following setup script:

```
#!/bin/bash

pip install pandas
pip install "ipykernel==6.12.1"
```

**Comment by astrojuanlu** [comment]
The problem does not seem to come from the ipykernel version, but from pip uninstalling the existing one.

This showcases the issue:

```
#!/bin/bash

pip install pandas
pip install "ipykernel==6.13.0"
```

but this doesn't:

```
#!/bin/bash

mamba install pandas -c conda-forge -y
mamba install "ipykernel==6.13.0" -c conda-forge -y
```

**Comment by astrojuanlu** [comment]
And finally, the problem is that pip ignores conda pinnings, and so we can't really stop users from doing this:

```
#!/bin/bash

# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#preventing-packages-from-updating-pinning
echo "ipykernel 6.9.1" >> /opt/conda/conda-meta/pinned

mamba update ipykernel  # Doesn't do anything, as expected
mamba install "ipykernel==6.13.0" -c conda-forge -y  # Fails, as expected

pip install "ipykernel==6.13.0"  # Proceeds, which will lead to errors
```

I don't think we can prevent this situation without the provisions of PEP 668 ([under consideration](https://discuss.python.org/t/pep-668-marking-python-base-environments-as-externally-managed/10302?u=astrojuanlu)). Debugging why this happens seems worthwhile too.

**Comment by astrojuanlu** [comment]
It definitely has nothing to do with the versions I believe. The problem also happens if one reinstalls the same version with pip:

```
#!/bin/bash

pip install pandas
pip uninstall -y ipykernel && pip install "ipykernel==6.9.1"
```

(6.9.1 is the one originally available in the environment)

**Comment by astrojuanlu** [comment]
Okay, now I know: `pip install ipykernel` places a `kernel.json` with the wrong path ❗ but a `python -m ipykernel install --sys-prefix` fixes the issue.

To demonstrate:

```
#!/bin/bash

pip install pandas

# Working kernel
cat /opt/conda/share/jupyter/kernels/python3/kernel.json

# Wrong argv, even if reinstalling the same version
pip uninstall -y ipykernel && pip install "ipykernel==6.9.1"
cat /opt/conda/share/jupyter/kernels/python3/kernel.json

# Fixes it
python -m ipykernel install --sys-prefix
cat /opt/conda/share/jupyter/kernels/python3/kernel.json
```

Useful for diagnostics:

```
# https://stackoverflow.com/questions/43561536/ipython-get-list-of-all-kernels-user-default
import jupyter_client
manager = jupyter_client.kernelspec.KernelSpecManager()
specs = manager.find_kernel_specs()
path = specs["python3"]

!cat "$path"/kernel.json
```
