### ISSUE TITLE
Shortcut Customization 

### ISSUE THREAD

**Issue by kingabzpro** [orchest/orchest#429]
**Describe the solution you'd like**  
change existing shortcuts to the one people are used to. 

**What does your solution aim to solve?**  
for a photoshop user its hard for me to use space for panning. 

**Describe alternatives you've considered**  
Allow us to change shortcuts.

**Additional context**

**Comment by ricklamers** [comment]
Great idea! But we are keen on first getting really good defaults and providing customization later.
