### ISSUE TITLE
App initialization inconsistency

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#440]
The `flask` apps for the `orchest-webserver`, `orchest-api`, `auth-server` are initialized in an inconsistent way, where with initialization we intend the respective `create_app` function, which does not take a configuration as an argument for the `orchest-webserver`, while it does for the other 2 services. This leads to trickle down inconsistencies, for example during testing.

**Comment by yannickperrenet** [comment]
I consider this fixed in #642.
