### ISSUE TITLE
Updated job name is not used after duplicating a job

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#466]
**Describe the bug**  
Updated job name is not used after duplicating

**To Reproduce**  

1. Create a job
2. Duplicate that job
3. Change the name of the job
4. Submit the job
4. See the name change has not been saved when submitting the job

**Expected behavior**  
The name of the job in the input field should be used.

**Comment by yannickperrenet** [comment]
It not only happens when duplicating a job.

**To Reproduce**
1. Create a job
2. Change the job name
3. Submit the job
4. See the name change has not been saved when submitting the job
