### ISSUE TITLE
AGPL implications for use in a closed source system

### ISSUE THREAD

**Issue by colecloudtostreet** [orchest/orchest#491]
I'm not very familiar with the AGPL. Can pipelines built on Orchest be used in a closed source system?

**Comment by ricklamers** [comment]
Hi @colecloudtostreet. _Usage_ in a closed source system should be fine.

AGPL is really about when you make modifications to Orchest and make that modified version available to users.

A nice TLDR https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)

I.e. you should be fine if you’re just running pipelines as part of a closed source system and not modifying Orchest itself.

If you were to modify Orchest and make that modified version available to users, you are required to make the modified source available under the same AGPL license.

At the risk of stating the obvious, making changes to code that’s inside a pipeline in Orchest does not constitute making changes _to Orchest itself_.
