### ISSUE TITLE
JupyterLab build hangs when sessions are active

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#500]
**Describe the bug**  
JupyterLab build hangs when sessions are active

**To Reproduce**  

1. Makes sure you have active sessions
2. Try to build JupyterLab
3. Build is greyed out and nothing happens

**Expected behavior**  
Sessions should be stopped on user confirmation and JupyterLab build should commence.

**Environment**
- OS: Linux
- Browser: Chrome
- Version: 2021.09.7
- Environment: prod, cloud

**Comment by yannickperrenet** [comment]
Can confirm, was about to make an issue :+1:
