### ISSUE TITLE
Remove jQuery usage

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#524]
**Describe the solution you'd like**  
In a couple of places, we use jQuery in components to handle some events or browser incompatibility issues.

It's a net negative for the codebase and in some places like the PipelineView component, it was "abused" in order to get good performance. I think we can get rid of jQuery entirely to clean up code to be more "pure" React. It partially stems from my initial unfamiliarity with advanced React event handling when I first implemented some of Orchest, so it's not always used for good reason.

**What does your solution aim to solve?**  
jQuery tech debt.

**Describe alternatives you've considered**  
Leaving it in.

**Comment by mausworks** [comment]
Fixed in #1143 :tada:
