### ISSUE TITLE
Make it easy to duplicate a step

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#534]
**Is your feature request related to a problem? Please describe.**  
It's cumbersome to create the same step twice.

**Describe the solution you'd like**  
Add a button to duplicate a step in the pipeline editor.

**Ideas**
We could combine this with some other ideas in a context menu (right click).

_Credit to Serhii Ostapchuk for contributing this on Slack._

**Comment by yannickperrenet** [comment]
> in a context menu (right click).

I really like this. We could even combine this with #429 and #519 and use `<Ctrl> + C` to copy the step.

**Comment by yannickperrenet** [comment]
Related to #589.

**Comment by yannickperrenet** [comment]
A context menu has been included in release `v2022.05.4` which makes it possible to duplicate a step by right-clicking on it to open the context menu.
