### ISSUE TITLE
Allow clicking of "JupyterLab" while session is starting

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#542]
**Describe the solution you'd like**  
Allow clicking of "JupyterLab" while session is starting

**What does your solution aim to solve?**  
The "I know what I want to do, but I can only say that I want to do it after something is done" is quite frustrating. If waiting is inevitable we should at least allow users to specify what needs to happen after the wait is over.

The case of the "Switch to JupyterLab" button is such an example. The page already supports waiting for the session to come up, so the change should be minimal.

**Comment by yannickperrenet** [comment]
This has been implemented.
