### ISSUE TITLE
Can't see which project you're in in JupyterLab and pipeline editor

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#552]
**Describe the solution you'd like**  
Add hint to the UI what the current project is in the JupyterLab/pipeline editor view.

**What does your solution aim to solve?**  
Can't see which project you're in in JupyterLab and pipeline editor

**Comment by yannickperrenet** [comment]
The project selector has been added to be present in the top bar in all views in #783. So this issue is solved.

Example in JupyterLab:
![image](https://user-images.githubusercontent.com/26223174/171914720-313ddeba-4f73-4075-a24b-0a905474a0a6.png)
