### ISSUE TITLE
Docker networking issues for Mac

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#56]
https://github.com/docker/docker-py/issues/2696

**Comment by yannickperrenet** [comment]
@ricklamers Could you (try to) verify that with the new version of Docker Desktop this issue is solved?

For reference, see: https://github.com/docker/docker-py/issues/2696#issuecomment-736660016 and [Docker for Mac release notes](https://docs.docker.com/docker-for-mac/release-notes/).

**Comment by ricklamers** [comment]
Fixed here on Docker for Desktop (3.0.4) on macOS. With Docker Engine version 20.10.2, build 2291f61.
