### ISSUE TITLE
Glitch in `connections` section in step properties

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#566]
**Describe the bug**  
This is definitely an edge case!

**To Reproduce**  

1. Open the pipeline editor
2. Create three steps, naming them "A", "B" and "C"
3. Don't connect the steps yet!
4. Open the properties pane of step "C"
5. Connect step "A" and "B" to "C"
6. Try to drag the connections in the properties pane

Note that dragging the connections in the properties pane is not possible. Close the properties pane and open it again and see that it now works.

**Expected behavior**  
Dragging should work.

**Screenshots**  
The pipeline in the reproduce steps:

![image](https://user-images.githubusercontent.com/26223174/143610072-db0143d8-a733-4d3a-92c6-ac747bb68a61.png)

**Comment by mausworks** [comment]
Should be fixed in this commit: https://github.com/orchest/orchest/pull/1147/commits/a41ca590b2442ea6079fbc7640611422c285f94d, and will be merged with the new UI.
