### ISSUE TITLE
Make it easier to inspect files of pipelines that are in the project but not assigned to any step

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#575]
**Describe the solution you'd like**  
Make it easier to inspect files of pipelines that are in the project but not assigned to any step ... (in jobs that are running/have run)

**What does your solution aim to solve?**  
If you import code that's part of your project it's hard to inspect when it's part of a job if that code is not assigned to a pipeline step.

**Comment by yannickperrenet** [comment]
This will be solved by #612. We will track further progress there.
