### ISSUE TITLE
Invalid request: Backing out of auth with google to login with password 

### ISSUE THREAD

**Issue by nickdickinson** [orchest/orchest#579]
**Describe the bug**  
![image](https://user-images.githubusercontent.com/1900032/144995591-e81ce2ff-f261-4ae7-a29c-726410f4fa7f.png)
invalid_request: You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn't find your session. Try logging in again from the application and if the problem persists please contact the administrator.
TRACKING ID: 9c497d2bd2c4026a26f2

**To Reproduce**  

1. Go to 'login'
2. Click on 'google'
3. When it presents 'this account exists with a different login method, go back...', go back with the browser button 

**Expected behavior**  
A login screen where one can enter a password or choose a method

**Screenshots**  
See above.

**Environment**

- OS: Windows 10
- Browser: Chrome 
- Version: 96.0.4664.45 (Official Build) (64-bit)
- Environment: Production
- Logs: No idea! This is from front end as a user
- 
**Additional context**

**Comment by nickdickinson** [comment]
And interestingly, just noticing there is no way to login as it gets stuck in a loop when I click on sign in on the front page.

**Comment by iannbing** [comment]
@nickdickinson Thanks for reporting this. The solution to this situation is to log out (remove your current session), and log in again with the right method. Indeed it should have been better if the UI guides you back to login screen. We've added a button "LOG IN WITH DIFFERENT METHOD" in this screen. Clicking this button will log you out, and thus navigate you back to login screen.

To break the indefinite loop, simply visit https://cloud.orchest.io again to see the "this account already exists" screen. And click the aforementioned button. Then you should be able to see the login screen again.

Feel free to re-open the issue if the issue persists.
