### ISSUE TITLE
Untagged environment images cause problems with old Orchest deployments

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#595]
**Describe the bug**  
Untagged environment images cause problems with old Orchest deployments

**To Reproduce**  

1. Go to Environments
2. Build environment
3. Try to start the kernel based on that environment from JupyterLab
4. See failure

It happens when the Orchest version is older than the latest release (v2021.12.1) which ships the latest Enterprise Gateway and latest Enterprise Gateway kernels (2.5.2).

**Expected behavior**  
Either the Enterprise Gateway needs to be updated to 2.5.2 or the environment images needed to be tagged to stay on 2.3.0.

**Comment by ricklamers** [comment]
Update: this might only impact people with custom images/highly customized environments.

**Comment by yannickperrenet** [comment]
> Either the Enterprise Gateway needs to be updated to 2.5.2 or the environment images needed to be tagged to stay on 2.3.0.

The EG is currently on `2.5.2` and the environment images are as well. I failed to reproduce this error so I will close it (for now?).
