### ISSUE TITLE
Environment "peek with terminal" feature

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#611]
**Is your feature request related to a problem? Please describe.**  
The problem is that often you don't know the details of how things are organized in a container image. So if you're extending either `orchest/base-image-py` or a custom image. It often requires trial and error to get the `setup_script.sh` worked out nicely.

**Describe the solution you'd like**  
The idea is to add the option to jump into an interactive terminal that spawns in the environment image (pre or post build, e.g. base image or the "fine tuned" image) to be able to look around, run a few `bash` command (like `pip show pandas`) to get a sense of how things are organized in the image.

This can help you fine-tune the `setup_script.sh` in a much more time-effective way compared to re-running the `setup_script.sh` all the time.

**Describe alternatives you've considered**
What you can do now is run the "debug" commands as part of the `setup_script.sh` (by putting at the top, or uncommenting the "actual" command you want to run). This is pretty hacky and time-consuming.

**Comment by astrojuanlu** [comment]
Notice that, beyond "peeking" or looking around the environment, this would be useful to run CLI-based tools like meltano, dbt, and the like, as discussed in #938.

**Comment by astrojuanlu** [comment]
> Some tasks need to be run from the command line using dependencies installed in the environment. Examples include:
> 
> - Management commands of meltano, dbt, and more
> - Quick experiments running Python files from the command line to observe outputs
> - Application of linters (black, isort etc)
> 
> However, at the moment when opening a Terminal, the user gets dropped to an environment that does not contain any of the dependencies installed in the environment, which live in Docker containers spawned by Jupyter Enterprise Gateway. This confuses users that are used to have a terminal sitting next to their files with access to the same Python virtual environment.
> 
> In some sense, the current setup is more similar to a remote development setting, where the Python runtime lives inside a Docker container, but with the limitation that users can't connect to such runtime from the terminal.
> 
> The only workaround is to use either a Jupyter notebook or a Jupyter console (both attached to a kernel), but there are some rough edges:
> 
> - Terminal commands need to be prefixed by an exclamation mark `!`
> - Commands with interactive input block the kernel without possibility of typing such input
> - Limited autocomplete support

**Comment by astrojuanlu** [comment]
Reference to the upstream IPython issue that prevents interactive commands usage: https://github.com/ipython/ipython/issues/10499
