### ISSUE TITLE
Pipeline names can be made equal

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#613]
**Describe the bug**  
When creating a pipeline, we check whether the name is not already taken by another pipeline and display an error if it is. However, taking another route you can later rename the pipeline so that two pipelines have the same name.

**To Reproduce**  

1. Create a new pipeline with the name `Main`
2. Create another pipeline with name `not-Main`
3. Now open the pipeline `not-Main` and go to *Settings*
4. Inside the settings, change the *Name* from `not-Main` to `Main`
5. Press *save*
6. See that the renaming was successful.

**Expected behavior**  
Either we need to allow for pipelines to have the same name or to make it "impossible" (not sure what we do about direct filesystem changes to the pipeline definition) to change the name of a pipeline to make it equal (users could do this accidentally) to another. If anywhere we use the constraint that pipelines in a project have a distinct name, then things could break.

**Comment by ricklamers** [comment]
Pipeline names should be allowed to be equal. It's just the file paths that need to be unique.

**Comment by ricklamers** [comment]
> If anywhere we use the constraint that pipelines in a project have a distinct name, then things could break.

To my knowledge, we don't.

**Comment by yannickperrenet** [comment]
> Pipeline names should be allowed to be equal.

Then that is the fix to this issue imo :+1:

**Comment by yannickperrenet** [comment]
One thing to note is that when creating a job, you need to select the pipeline for which you are creating the jobs. Having equal names makes it impossible to distinguish the pipelines in the current view (not sure whether we should let the user "self-inflict" this)

![image](https://user-images.githubusercontent.com/26223174/147253226-675a6439-b08e-4ae9-ab7a-a7ae90924280.png)

**Comment by ricklamers** [comment]
Since you can import arbitrary pipelines into a project with arbitrary names we can't control for pipelines not having the same names. The implication you sketch I think is fine. We could add the path as a fix, but I don't see why many people would have pipelines with the same names. So I think the edge case is acceptable.
