### ISSUE TITLE
Flash of invalid form entry

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#626]
**Describe the bug**
When you create a new pipeline for a short moment the form flashed red signaling an invalid field entry.

**Expected behavior**
The form should disappear after successful creation and not flash red during its disappearance.

**To Reproduce**

1. Go to Pipeliens
2. Click on Create pipeline
3. Enter a valid name/path
4. Submit form
5. See quick red flash of field

**Screenshots**

**Environment**

- OS (e.g. macOS): Linux
- Browser (e.g. Chrome): Brave
- Orchest's version (in the settings page): v2021.12.3

**Comment by yannickperrenet** [comment]
With the removal of the pipelines page this issue has been resolved. I've also checked the new "create pipeline" functionality, but nothing strange happens there :+1:
