### ISSUE TITLE
Support touch events in the pipeline editor

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#648]
**Describe the problem this improvement solves**
When using Orchest on a touch enabled device you cannot navigate the pipeline

**Describe the solution you'd like**
Support standard touch gestures

**Comment by yannickperrenet** [comment]
This includes panning in the pipeline editor using a touch pad :ok_hand:

**Comment by iannbing** [comment]
Some details would help further clarify this requirement.

When panning takes place, scrolling to zoom in/out has to be replaced by other solutions, because panning up and down is equivalent to mouse wheel up and down.

- Touch device: panning and pinch to zoom in/out.
- Traditional mouse: 
    - moving canvas: space bar + mouse primary key down, or mouse secondary key down. 
    - zoom-in/out: mouse wheel

**Comment by yannickperrenet** [comment]
I like those requirements :+1:
