### ISSUE TITLE
Link to the "contributor guidelines" doesn't work

### ISSUE THREAD

**Issue by fshabashev** [orchest/orchest#667]
**Describe the bug**
In the README.md file the link to the "contributor guidelines" doesn't work
https://github.com/orchest/orchest/blob/master/README.md

**Expected behavior**

the link should work

**To Reproduce**
Go to README.md and click "contributor guides" link ( see attached screenshots) 

**Screenshots**
![Screen Shot 2022-01-25 at 8 37 59 PM](https://user-images.githubusercontent.com/6548211/151056249-6a5d9d8a-2aca-4ad0-a25e-f77546e8b0fc.png)
![Screen Shot 2022-01-25 at 8 38 26 PM](https://user-images.githubusercontent.com/6548211/151056261-80ad9c82-893e-4540-a971-0db4059d046a.png)

**Environment**

not relevant

**Comment by ricklamers** [comment]
Good catch! Fixed it https://github.com/orchest/orchest/commit/49b272da6d68a14cd6e057048291c8a736f963a9
