### ISSUE TITLE
Add ability to hide (secret) environment variables

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#679]
**Describe the feature you'd love to have in Orchest**
Add ability to hide (secret) environment variables

**Is your feature request related to a problem? Please describe.**
Sometimes you’d rather not display env vars on screen as they can contain sensitive data.

**Additional context**
We should make marking environment variables as sensitive optional or make it the default. If it can be toggled we’d need to understand where to store that state and at what level (e.g. same env var name have different behavior across projects?)

**Comment by yannickperrenet** [comment]
> We should make marking environment variables as sensitive optional or make it the default.

I am in favor of hiding environment variable values by default and add an :eye_speech_bubble: icon to show the value.
