### ISSUE TITLE
Increase table rows count per page selector to larger range

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#700]
**Describe the problem this improvement solves**
Sometimes you really would like to load many results to a page. Currently, we have '5, 10, 25'.

**Describe the solution you'd like**
I think a more reasonable set of choices would be '10, 25, 100, 500'.

**Comment by yannickperrenet** [comment]
@iannbing I figured I quickly make this change by changing the options in the DataTable ([#L866](https://github.com/orchest/orchest/blob/master/services/orchest-webserver/client/src/components/DataTable.tsx#L866)), however changing the option in the table to `500` (or any other large number) makes the page render extremely slow.

I do think that providing an option to show `100` options is definitely a good one.

**Comment by iannbing** [comment]
Rendering large number of rows requires some optimization. [MUI recommends react-virtulized](https://v5-0-6.mui.com/components/tables/#virtualized-table).

**Comment by yannickperrenet** [comment]
> Rendering large number of rows requires some optimization

The issue of slow rendering even happens when there are 0 items. So it is not even rendering a large number of rows.

Would this be easy to include? If it is then I think we should do it so we can offer an option of `100` rows.

**Comment by iannbing** [comment]
@yannickperrenet It's unclear to me which part of the rendering is seen slow in your case. I guess it was the "loading skeletons". While DataTable is fetching data, 100 rows with **animated** skeleton cells are rendered.  I made a PR to limit the animated rows to 25. T100 rows seem quite okay to me. Please try it out and let me know if it still shows slow rendering.

I'm not sure about the numbers beyond 100 from UX perspective. If there's such a case, search/filter would be more helpful than allowing 500 rows imo.
