### ISSUE TITLE
Jupyter notebook get blank after editing it in a pipeline

### ISSUE THREAD

**Issue by rodrigoacastro** [orchest/orchest#725]
**Describe the bug**
When using orchest in an EC2 instance, sometimes the jupyter notebook suddenly gets blank, and I lose hours of work. 

**Expected behavior**
I expected that the notebooks would keep their information properly.

**To Reproduce**
- create a pipeline
- configure the environment
- create the jupyter notebooks for the pipeline
- close the connection and try again later
- edit the notebook and save it

**Environment**
- Linux OS in EC2 instances on AWS

**Comment by yannickperrenet** [comment]
Hi @rodrigoacastro, I am sorry to hear that.

Does the issue you have experienced sound similar to #503?

**Comment by rodrigoacastro** [comment]
Hello,

To be honest, I am not sure. When it happened, I was sure that the notebook saved the changes, but the next time I opened the notebook I had lost my code. I thought that it was supposed to save every minute or so, but it didn't happen. 

Sometimes I had a backup offline or simply worked offline and updated the notebook online at the last moment, which was the strategy I resorted to after a few missing codes.

**Comment by yannickperrenet** [comment]
The workflow you describe is indeed not the ideal workflow and you should be able to use the integrated JupyterLab without hiccups. 

Did you install Orchest yourself on the EC2 instance in AWS? And is the Orchest `userdir` backed by a root device volume or are you mounting an EBS volume to the instance to store the data? I don't think it is related but would be good information to have so we can at least conclude that there are no issues with the deployment. 

Thanks again for bringing the issue to our attention.

**Comment by rodrigoacastro** [comment]
Indeed, I have installed Orchest on the EBS of an EC2 instance on AWS on the root disk which comes with the instance. I even tried to scale the machine because it was reaching the limit of the CPU very quickly, so I small machine wouldn't work well. The scaling did not solve this problem, though.

**Comment by yannickperrenet** [comment]
Thanks for the info. We have been using `t2.large` instances for our Orchest deployments which work great depending on the workloads you are running.

I will look into this issue and see whether there is anything we can do :+1:

**Comment by rodrigoacastro** [comment]
I do not remember seeing this dialogue, to be honest, but it could be an interval of days indeed. It has been a while since I used it. 
But I didn't know the default autosave period was 120 seconds and that it could be changed. Usually, I used to (try to) save the notebook and come back later just to find out that the notebook was empty, totally blank.

**Comment by yannickperrenet** [comment]
> We used a docker composer with all the dockers in the same machine.

Could you elaborate on this? Did you write a custom Docker Compose to run Orchest or did you add parts of Orchest to the compose file together with other applications?

Orchest doesn't change any of your Notebook files (except when running pipelines that have Notebooks assigned to steps), so if they were once written to disk then Orchest won't change them. I am wondering whether other applications from the Docker Compose get the same files mounted and change permissions causing the page to appear blank in the JupyterLab editor. 

I will verify what happens to files in JupyterLab if their permissions were changed outside of JupyterLab.

**Comment by astrojuanlu** [comment]
I believe this _might_ be related to https://github.com/jupyterlab/jupyterlab/issues/11662, and in turn, to the other weird behaviours we are observing at #503.
