### ISSUE TITLE
Add indication that `project-dir` files can be used in environment builds 

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#726]
**Describe the problem this improvement solves**
The functionality that you can use files from your project directory when building environments is not clear from the UI ([docs](https://docs.orchest.io/en/stable/fundamentals/environments.html#important-paths-inside-environments)). For example the fact that the following works is unclear (and it is unlikely people will try this without having stumbled on the docs):
```bash
#!/bin/bash
pip install -r requirements.txt
```

**Describe the solution you'd like**
In #612 we want to make the concept clear that pipeline steps simply point to files. Maybe we can extend this to the environment set-up script as well?

**Comment by astrojuanlu** [comment]
I understand that https://github.com/orchest/orchest/commit/9100f076e028d22a73735be2634daca4fed56206 moved the docs, but we did not make any changes to the UI, right? I still contend that it's not very easy to discover (unless we do point users to the docs from the UI)
