### ISSUE TITLE
Improve relevancy of columns in table of `/projects`

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#736]
**Describe the problem this improvement solves**
Not all information in the table is actually useful. We should try to only display valuable information and reducing noise.

**Describe the solution you'd like**
Listing number of "active jobs" instead of "jobs" and removing the "environments" column.

**Screenshots**
So changing the columns of this table:
![image (8)](https://user-images.githubusercontent.com/26223174/155168260-1ed8e64d-c3c9-4fb5-af6b-b16ca8304f4e.png)

**Comment by mausworks** [comment]
[This is solved in the new design](https://github.com/orchest/orchest/pull/1090#issuecomment-1177492132). :+1:
