### ISSUE TITLE
An example docker-compose file to start Orchest

### ISSUE THREAD

**Issue by tdoan2010** [orchest/orchest#737]
**Describe the feature you'd love to have in Orchest**
Currently, to setup Orchest, I have to do it via the `orchest-ctl` with `./orchest install` and `./orchest start`. After that, 6 containers start up and I can use the system.

Although this is a simple way to start, I need more information about each container, e.g. how they are configured, how they communicate with each other, and so on. A `docker-compose.yml` file would provide me such information. Knowing this information would allow me to deploy the system in a more flexible way.

**Additional context**
We plan to offer Orchest-as-a-Service, therefore we need more information regarding deployment so that we can deploy it on our infrastructure. For example, it would be great if we could connect Orchest to our running Jupyter-Notebook service, or deploy Orchest on our k8s.

**Comment by ricklamers** [comment]
@tdoan2010 Thanks for enquiring! We're actually moving away from Docker for managing the containers and are shifting to `k8s`. The goal is an idiomatic `k8s` helm deployment option to make it easy to make Orchest part of a bigger whole.

You can follow overall progress here: https://github.com/orchest/orchest/pull/623

**Comment by astrojuanlu** [comment]
Hi @tdoan2010! Apart from what @ricklamers says, let me give a few extra pointers so you can better understand how Orchest works _at the moment_. Even though this advice will become obsolete after #623 is merged (which we are targeting for the coming weeks), I hope it clarifies the current architecture:

`./orchest` is a wrapper around the `orchest-ctl` image that creates a custom network, mounts the Docker socket, and mounts several user directories to store persistent configuration:

https://github.com/orchest/orchest/blob/26d381d69d6839a8fd902d8b7c8a05462862530e/orchest#L62-L73

The `orchest-ctl` entrypoint is a Typer script defined [here](https://github.com/orchest/orchest/blob/26d381d/services/orchest-ctl/app/cli/main.py), and in particular `orchest start` comes from here:

https://github.com/orchest/orchest/blob/26d381d69d6839a8fd902d8b7c8a05462862530e/services/orchest-ctl/app/cli/start.py#L101

Orchest then proceeds to spawn a bunch of containers from here:

https://github.com/orchest/orchest/blob/26d381d69d6839a8fd902d8b7c8a05462862530e/services/orchest-ctl/app/orchest.py#L270-L277

Which, in the end, wraps [`docker.client.DockerClient`](https://docker-py.readthedocs.io/en/stable/client.html):

https://github.com/orchest/orchest/blob/26d381d69d6839a8fd902d8b7c8a05462862530e/services/orchest-ctl/app/docker_wrapper.py#L349-L353

Hope this helps! If you want to discuss more, feel free to [join our Slack workspace](https://join.slack.com/t/orchest/shared_invite/zt-g6wooj3r-6XI8TCWJrXvUnXKdIKU_8w).
