### ISSUE TITLE
Error Starting Kernel when edit in jupyter lab

### ISSUE THREAD

**Issue by huangkai31** [orchest/orchest#757]
**Describe the bug**
./orchest start 
import quickstart project
open pipeline , open step and edit in jupyterlab
in jupyterlab show error:
Error Starting Kernel
HTTP 500: Internal Server Error (Error attempting to connect to Gateway server url 'http://jupyter-EG-f6249899-51e3-474b-0915b350-b929-4cbd:8888'.  Ensure gateway url is valid and the Gateway instance is running.)

**Expected behavior**
should start a kernel

**Screenshots**
![image](https://user-images.githubusercontent.com/1758277/156696572-f30c8ee3-75ab-4d15-b253-e40f8a803d27.png)

**Environment**

- OS (e.g. macOS): win10 21h1 with wsl2 (ubuntu 20.04.2)
- Docker 20.10.12
- Browser (e.g. Chrome): edge
- Orchest's version (in the settings page): v2022.02.9

**Comment by huangkai31** [comment]
Detailed version of all the images
orchest/jupyter-enterprise-gateway:latest   : v2021.06.3
orchest/jupyter-server:latest               : v2022.03.0
orchest/memory-server:latest                : v2022.03.0
orchest/session-sidecar:latest              : v2022.03.0
orchest/update-server:latest                : v2021.10.2
orchest/orchest-api:latest                  : v2021.10.2
orchest/orchest-webserver:latest            : v2022.03.0
orchest/celery-worker:latest                : v2021.12.0
orchest/auth-server:latest                  : v2022.03.0
orchest/file-manager:latest                 : v2021.12.0
orchest/nginx-proxy:latest                  : v2021.10.2
orchest/base-kernel-py:latest               : v2022.03.0

**Comment by huangkai31** [comment]
$ docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED              STATUS              PORTS                                                 NAMES
44c65301ff75   orchest/jupyter-server:latest        "/start.sh --allow-r…"   29 seconds ago       Up 27 seconds                                                             jupyter-server-f6249899-51e3-474b-0915b350-b929-4cbd
df529b74fb19   orchest/jupyter-enterprise-gateway   "tini -g -- /usr/loc…"   31 seconds ago       Up 29 seconds       8888/tcp                                              jupyter-EG-f6249899-51e3-474b-0915b350-b929-4cbd
9b7c5792c43f   orchest/session-sidecar:latest       "/bin/sh -c 'umask 0…"   33 seconds ago       Up 31 seconds                                                             session-sidecar-f6249899-51e3-474b-b65e-018fb8084cd5-0915b350-b929-4cbd-b0d4-763cac0bb69f
f0c9ac2afc96   orchest/memory-server:latest         "python app/main.py"     34 seconds ago       Up 33 seconds                                                             memory-server-f6249899-51e3-474b-b65e-018fb8084cd5-0915b350-b929-4cbd-b0d4-763cac0bb69f
b41334754d1f   orchest/nginx-proxy:latest           "/usr/bin/openresty …"   About a minute ago   Up About a minute   0.0.0.0:8000->80/tcp                                  nginx-proxy
22f85073f4aa   orchest/orchest-webserver:latest     "/entrypoint.sh /sta…"   About a minute ago   Up About a minute   80/tcp                                                orchest-webserver
6b9954b374c3   orchest/orchest-api:latest           "/entrypoint.sh /sta…"   About a minute ago   Up About a minute   80/tcp                                                orchest-api
de5d439859bb   orchest/auth-server:latest           "/entrypoint.sh /sta…"   About a minute ago   Up About a minute   80/tcp                                                auth-server
7be6fee1facd   orchest/celery-worker:latest         "/usr/bin/supervisor…"   About a minute ago   Up About a minute                                                         celery-worker
7536e652281b   postgres:13.1                        "docker-entrypoint.s…"   About a minute ago   Up About a minute   5432/tcp                                              orchest-database
4e015fb20289   rabbitmq:3                           "docker-entrypoint.s…"   About a minute ago   Up About a minute   4369/tcp, 5671-5672/tcp, 15691-15692/tcp, 25672/tcp   rabbitmq-server
01162355da71   orchest/file-manager:latest          "/bin/sh -c 'umask 0…"   About a minute ago   Up About a minute   80/tcp                                                file-manager

**Comment by yannickperrenet** [comment]
Hi @huangkai31 thanks for raising this issue!

Your issue is related to #496. It would be great if we can continue the conversation there.

> Detailed version of all the images

Based on your output it seems like not all images are running on the same version (which is required for Orchest to run correctly). The remedy should be to run `./orchest update` to get all images on the same version again. 

Please reply in the other issue if that doesn't fix it for you.

**Comment by huangkai31** [comment]
@yannickperrenet  you are right, it seems the version is important, so I build it with v2022.03.0 and now the problem is solved.

**Comment by yannickperrenet** [comment]
@huangkai31 Great to hear that everything is working for you now :smiley_cat:
