### ISSUE TITLE
Document `conda` as supported installer for environments

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#759]
Right now [we document how to install packages in environments](https://docs.orchest.io/en/latest/fundamentals/environments.html#using-a-different-python-version) using `pip` and `apt`. However, it would be good to (1) document conda as supported as well, and (2) add it to the example input:

https://github.com/orchest/orchest/blob/c37eb86e510a6c319261c1f158a60e89bea7b86c/lib/python/orchest-internals/_orchest/internals/config.py#L89-L95

At the moment, conda is mentioned at the end of the page to change the Python version, but it's prefixed by a scary

> Bringing your own fully custom environment image is not recommended as Orchest requires a certain structure of the image to work correctly

If this is a real concern (and I'm sure it is), we should probably make more explicit what versions of jupyterlab etc are supported in Orchest, and what users shouldn't change. Or, even better, [pin those packages as suggested in the docs](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#pinning-packages):

> In the environment's `conda-meta` directory, add a file named pinned that includes a list of the packages that you do not want updated.

**Comment by yannickperrenet** [comment]
> However, it would be good to (1) document conda as supported as well, and (2) add it to the example input:

When it comes to these points, (1) I agree with, and (2) I don't completely agree with but would love to hear your thoughts. What I don't like about (2) is that it convolutes the example input. I would rather give a single recommendation than showing all possible ways to install something. Sure in the docs we can explain multiple installation methods, but in the example input (imo) it is best to direct the user to a single solution.

**Comment by astrojuanlu** [comment]
If we want to give only one solution, then I'm afraid we should stick to conda/mamba rather than pip. Some machine learning packages are famously not installable through pip, for good reasons:

https://medium.com/rapids-ai/rapids-0-7-release-drops-pip-packages-47fc966e9472

The post above is almost 3 years old and some things have luckily improved. It was written at a time in which tensorflow and pytorch were uploading invalid wheels to PyPI https://github.com/pypa/warehouse/issues/5420. To my knowledge, the situation has improved after the rollout of manylinux2010 and manylinux2014 tags - but still, wheels offer limited support that library authors have asked for a long time https://github.com/pypa/packaging-problems/issues/25 and so conda/mamba is nowadays a better installer for machine learning and scientific workflows.

Sane human beings though don't know about all these details and they couldn't care less as long as the thing installs.

On the other hand, I _think_ that, if people see they can do `conda/mamba install x`, they will understand that they could resort to pip. The opposite doesn't hold - I was not sure myself if `conda install x` would break in Orchest before trying it.

**Comment by yannickperrenet** [comment]
Makes sense. We definitely want to tailor to our audience so I would be fine going with `conda` instead (as the only solution we present in the example set-up script).

**Comment by astrojuanlu** [comment]
...but then of course, if one tries something like `conda install -y pytorch`, the endless `Solving environment` prompt kicks in 🙃 probably because all the packages from the `base` environment are installed from `conda-forge`.

I then tried `conda install -y mamba`, which is slow but not painfully so (~2 minutes on my computer), but then `mamba install -y pytorch -c conda-forge` was still slow as hell, because it was pulling `mkl` and all on the `base` environment we have `openblas`.

I'm in the middle of some trial and error to understand what install command would do the trick, but in any case, it looks like recommending `conda` as the default is premature. I'll focus on (1), documenting it with its caveats, and at some point in the future we can work on (2).

**Comment by astrojuanlu** [comment]
For future reference, I think I just got unlucky:

- `conda install -y mamba -c conda-forge` retrieves a super old version at the moment which does not give very informative error messages. Still trying to understand why.
- conda-forge `pytorch` does depend on MKL on Linux, and therefore installing it with openblas is not really an option.

I will deal with these problems separately.
