### ISSUE TITLE
Can not start the orchest web ui?

### ISSUE THREAD

**Issue by mullerhai** [orchest/orchest#762]
**Environment**

- OS (e.g. macOS):  centos 7.3
- Browser (e.g. Chrome):
- Orchest's version (in the settings page): latest

after I do  this 
```
git clone https://github.com/orchest/orchest.git && cd orchest

# Check out the version you would like to build.
git checkout v2021.11.2

# Build Orchest's Docker containers from source (in parallel).
scripts/build_container.sh

# Start Orchest. Note that it will pull additional containers that
# Orchest depends on, such as `postgres`.
./orchest start
```

```
(modelenv) [root@centos orchest]# ./orchest start
Before starting Orchest, make sure Orchest is correctly installed. Run:
        orchest install
(modelenv) [root@centos orchest]# ./orchest install
Installing Orchest...
Pulling images: 3/3|###################################################|
Checking whether all containers are running the same version of Orchest.
Getting versions of all containers...
orchest/jupyter-enterprise-gateway:latest   : v2021.11.2
orchest/jupyter-server:latest               : v2022.03.0
orchest/session-sidecar:latest              : v2022.03.0
orchest/update-server:latest                : v2021.11.2
orchest/orchest-api:latest                  : v2021.11.2
orchest/orchest-webserver:latest            : v2022.03.0
orchest/celery-worker:latest                : v2022.03.0
orchest/auth-server:latest                  : v2022.03.0
orchest/file-manager:latest                 : v2021.11.2
orchest/nginx-proxy:latest                  : v2021.11.2
Could not get version of all Orchest required images because some are
missing. Make sure Orchest is correctly installed:
        orchest install
Installation was unsuccessful.
Could not pull the specified set of images. Please make sure you have
enough available disk space.

(modelenv) [root@centos orchest]# ./orchest start
Before starting Orchest, make sure Orchest is correctly installed. Run:
        orchest install
(modelenv) [root@centos orchest]# ls
```
I  run  the  cmd [ ./orchest start]  ,repl  repeat tell me [orchest install ] ,I don't know why

**Comment by yannickperrenet** [comment]
Hi @mullerhai, I am sorry for the poor experience you are experiencing. 

The issue is as follows:
* You try to build from source. This install everything, except the Docker network required.
* `./orchest start` tells you to run `./orchest install`, which then proceeds pulling images that are on a different version than the ones you build

End result being an invalid state for Orchest to start.

I will come back to you in a short moment with steps to fix this.

**Comment by yannickperrenet** [comment]
Steps that should fix the issue you are experiencing:
1.    `docker network create orchest` 

       It could be that this raises the issue: `Error response from daemon: network with name orchest already exists`. Feel free to ignore this as it means that the network was installed when you ran `./orchest install`.
       
2. Build Orchest again: `git checkout v2022.03.0 && scripts/build_container.sh` (or use the specific version you want to build)
3. Start Orchest: `./orchest stop && ./orchest start`

Let me know whether this fixes things for you and I will make sure to update our docs. Thanks again for raising the issue.

**Comment by mullerhai** [comment]
> Steps that should fix the issue you are experiencing:
> 
> 1. `docker network create orchest`
>    It could be that this raises the issue: `Error response from daemon: network with name orchest already exists`. Feel free to ignore this as it means that the network was installed when you ran `./orchest install`.
> 2. Build Orchest again: `git checkout v2022.03.0 && scripts/build_container.sh` (or use the specific version you want to build)
>    This makes sure that all images are running the same version of Orchest again.
> 3. Start Orchest: `./orchest stop && ./orchest start`
> 
> Let me know whether this fixes things for you and I will make sure to update our docs. Thanks again for raising the issue.

After  I  do  like that ,the console  also  same as  pre time

**Comment by yannickperrenet** [comment]
I am not sure I understand what you mean. Are you saying the provided steps did not fix your issue?

In case they did not fix your issue, could you share they output of `./orchest start` and `./orchest version --ext`? Thank you.

**Comment by yannickperrenet** [comment]
We have migrated to a Kubernetes based backend. Therefore, the aforementioned steps would not work on any version newer than (and including) [v2022.03.7](https://github.com/orchest/orchest/releases/tag/v2022.03.7).

Let me know whether the issue persists for you. I'd be happy to help, even when looking to build a "pre-k8s" version.
