### ISSUE TITLE
Misleading "File load error" (case sensitivity?)

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#765]
**Describe the bug**
I sometimes get a "File load error" when I get to JupyterLab from the pipeline view even though the corresponding file is there. This is the relevant part of my Orchest pipeline definition:

```json
    "steps": {
        "e08a3640-d68b-4619-99a0-106610495dfc": {
            "environment": "fa7f7280-b8d2-47de-98b2-5db2fdf31f9d",
            "file_path": "Cohort retention analysis.ipynb",
            "incoming_connections": [],
            "kernel": {
                "display_name": "Streamlit Python 3",
                "name": "python"
            },
            "meta_data": {
                "hidden": false,
                "position": [
                    563.5,
                    432.5
                ]
            },
            "parameters": {},
            "title": "",
            "uuid": "e08a3640-d68b-4619-99a0-106610495dfc"
        }
    },
```

I suspect that the reason is case sensitivity in the notebook name.

**Expected behavior**
No error message should appear if the file already exists.

**To Reproduce**

1. Go to Pipeline view
2. Click on "New step"
3. Leave the title blank, create new step with file `"Some step.ipynb"`
4. Click "create file"
5. Click "edit in JupyterLab", see error saying `No such file or directory: some step.ipynb`
6. Open `Some step.ipynb` normally

**Screenshots**

![Screenshot 2022-03-07 at 15-15-33 JupyterLab · Orchest](https://user-images.githubusercontent.com/316517/157051256-14cbeca6-4548-4f94-aeef-a0441a0770a0.png)

(Took this screenshot after seeing the error, opening the file, switching to pipeline view, and getting back to the step again)

**Environment**

- OS (e.g. macOS): Linux Mint 20.3
- Browser (e.g. Chrome): Firefox 97.0.1
- Orchest's version (in the settings page): v2022.02.9

**Comment by yannickperrenet** [comment]
Issue is caused by the calling `toLowerCase` when parsing the query string:
https://github.com/orchest/orchest/blob/6856fe1cceb975d17ebb8570e27748da910c96b6/services/orchest-webserver/client/src/routingConfig.tsx#L240-L243

When I removed the `toLowerCase` call everything worked correctly (fixing this issue), but I am not sure whether this would break things elsewhere.

@iannbing @ricklamers Would be great if one of you could share why we need (or not) the `toLowerCase` :smile:

**Comment by yannickperrenet** [comment]
Thank you for the quick (and clear) response @iannbing.

The `fuzzy_filter` in the backend also calls `.lower()` on the given filter from the frontend:

https://github.com/orchest/orchest/blob/6e0862dd2bb0e5a878af3e676f7c59a41d1e25f6/services/orchest-api/app/app/utils.py#L805

and so removing it from the frontend would not break the edge case that you mention :+1: 

(I will create a PR in a moment.)
