### ISSUE TITLE
Auto-saving in pipeline settings to not happen after every typed character

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#770]
**Describe the problem this improvement solves**
When auto-saving after every character, then auto-formatting would lead to "strange" behavior. For example:

1. The pipeline parameters are `{}` (so go to the pipeline's settings)
2. Go into the dictionary like so: `{|}` (where `|` represents the cursor)
3. Press `<Enter>`
4. Expect to see:

    ```plain
    {
    }
    ```
    
    but actually see: `{}|`

(Thanks @fruttasecca.)
 
**Describe the solution you'd like**
Editing the pipeline parameters should behave as expected (for example editing the step parameters works fine).

**Comment by iannbing** [comment]
To clarify, PipelineSettings doesn't have auto-saving yet. PipelineSettings was not properly persisting user's input in general. This issue is addressed in #781.
