### ISSUE TITLE
Network errors when trying to start a custom kernel

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#777]
**Describe the bug**
When creating a custom image, I can't pick the corresponding kernel, since it gives a network error.

**Expected behavior**
I would expect to be able to use my custom kernel.

**To Reproduce**

1. Go to Environments
2. Create new environment called "Python 3 (alt)" with a custom base image `python:latest` (as advised) and Language = Python, leaving the set-up script empty
3. Open a pipeline with this environment, start the session, switch to JupyterLab
4. Start notebook with "Python 3 (alt)" kernel
5. Observe network error

**Screenshots**
Locally:
![Screenshot 2022-03-09 at 09-05-08 JupyterLab · Orchest](https://user-images.githubusercontent.com/316517/157398659-ac21c0ea-f264-4b99-a592-c1bd09505960.png)

On the cloud:
![Screenshot 2022-03-09 at 08-49-21 JupyterLab · Orchest](https://user-images.githubusercontent.com/316517/157398675-5a736f76-d398-4c63-9fed-03b0e0651c54.png)

**Environment**

- OS (e.g. macOS): Linux Mint 20.3
- Browser (e.g. Chrome): Firefox 97.0.2
- Orchest's version (in the settings page): v2022.03.0 (local), v2022.02.9 (cloud)

**Comment by astrojuanlu** [comment]
Found this while trying to debug gh-776.

**Comment by yannickperrenet** [comment]
I would say that this issue is expected, but we can definitely do a better job at explaining "how to bring your custom environment". When using a custom environment for [services](https://docs.orchest.io/en/latest/fundamentals/services.html) then your approach should work, however, for kernels additional dependencies are required (i.e. kernels need to be recognized and connected to by the Enterprise Gateway and the Orchest SDK needs to be installed as well). 

I will leave the issue open so we can track progress on better supporting custom environments.

**Comment by yannickperrenet** [comment]
For completeness, a list of requirement to bring your own custom environment image for pipeline steps:

- Include orchest-sdk
- Include the [runner](https://github.com/orchest/orchest/tree/965cae0814ded27f3599ab40ed65467e0f09e195/services/base-images/runnable-shared/runner) code from our code base to run kernels or scripts
- Include enterprise-gateway files for it to be able to connect to the kernel (needs to be kept in sync with the actual enterprise-gateway version we are running).

**Comment by yannickperrenet** [comment]
Relates to issue: [Unified approach for alternative Jupyter kernels like jupyter-xeus](https://github.com/orchest/orchest/issues/138#). Can possibly be picked up together, but at the time of writing this comment I consider it low priority.

**Comment by yannickperrenet** [comment]
I will close this issue in favor of #879. 

When it comes to bringing your own custom kernel (so creating a custom Environment that includes a custom kernel for you to use in JupyterLab), then I consider it something we don't have to cover for the time being as the majority of users are served just fine with the kernels that we currently support.
