### ISSUE TITLE
Julia support

### ISSUE THREAD

**Issue by loleg** [orchest/orchest#78]
As fan and user of the [language](https://github.com/topics/julia), and having seen this question already [mentioned on HN](https://news.ycombinator.com/item?id=24138311) it would be great to know what it would take to enable support for Julia notebooks - an environment which typically plugs right in with Python libraries. My impression right now is that we would need to add a base kernel image, similarly to [R support](https://github.com/orchest/orchest/tree/master/services/base-images/base-kernel-r).

**Comment by ricklamers** [comment]
This is definitely something we want to add. We would need to set up an Enterprise Gateway kernel for Julia similar to their R one: https://github.com/jupyter/enterprise_gateway/tree/master/etc/docker/kernel-r

I'll look into it this this week, it shouldn't be too difficult to add basic support as we architected Orchest to support this kind of expansion.

SDK support will be missing initially (for e.g. data passing or parameterization) but shouldn't be too hard to add later.

**Comment by ricklamers** [comment]
Basic Julia support is now shipped in v0.3.6: https://github.com/orchest/orchest/releases/tag/v0.3.6

Let us know what you think! :)

**Comment by ricklamers** [comment]
Some more details can be found in this PR: https://github.com/orchest/orchest/pull/85

To cite: 

> This commit adds Julia support to Orchest. The SDK for Julia (similar to the one for R) still needs be created.
> 
> With this PR users will be able to build Julia environments, run Julia scripts, and (interactively) run Julia based Notebooks.
