### ISSUE TITLE
User authentication/management does not work

### ISSUE THREAD

**Issue by laracabrera** [orchest/orchest#79]
When trying to create new users from Settings, clicking the button does not work as expected, as no request is sent to the auth service. Sending the POST request using *curl* works, as I've been able to create some user accounts this way.

The same thing happens at the Login page: clicking the Login button does not send any request to the auth service.

Note: I'm running Orchest with SSL enabled.

**Comment by ricklamers** [comment]
Good catch! This had to do with the <button type='button'> becoming the new default.

Fixed in https://github.com/orchest/orchest/commit/269e8bd6b82aea4faf28b9123eca7e27e06efb30. We'll push a release later today.
