### ISSUE TITLE
Kubernetes / Docker Swarm support

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#82]
In the future we'd like to support more advanced multi-node use cases by building on top of existing container orchestration abstractions. This issue will track progress on this particular feature and the decisions that are made around it.

**Comment by howie6879** [comment]
Look forward to this feature ✨

**Comment by yannickperrenet** [comment]
Kubernetes support is closed to being finished, check out the [`feat/k8s` branch](https://github.com/orchest/orchest/tree/feat/k8s).

**Comment by yannickperrenet** [comment]
Check out how to get started in our [Installation docs](https://docs.orchest.io/en/latest/getting_started/installation.html) :smile:
