### ISSUE TITLE
Improved job statuses

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#821]
**Describe the solution you'd like**

Other statuses and other icons so it is clearer to users what state their jobs are in.

**Screenshots**
After stopping a cron-job:

![image](https://user-images.githubusercontent.com/26223174/159050631-a5a27c88-a68c-4a97-9ff8-b22373437a10.png)

This raises the question: Did something fail? Is our production pipeline broken?

**Comment by astrojuanlu** [comment]
Maybe replacing the current "Cancelled" with 🛑 and "Failed" with :x: would help? I am often confused by this too.
