### ISSUE TITLE
Can we use PersistentVolume instead of PersistentVolumeClaim for userdir?

### ISSUE THREAD

**Issue by yosiasm** [orchest/orchest#834]
I want to get cookies stored in my browser that located in host, is there any possible way to get access to host from Orchest pods?

**Comment by yosiasm** [comment]
For now I run Rsync on the beginning of my pipeline to synchronize my project and host directory

**Comment by astrojuanlu** [comment]
Hi @yosiasm, thanks for opening this issue. To clarify, are you looking for easy local data synchronization/passing between the local file system and Orchest? We agree that having to do `rsync` is a bit painful.

**Comment by yosiasm** [comment]
Hi @astrojuanlu, thanks for your response. That's correct and more precisely, I want to store all of my script and other file dependencies in the local file system. Like we connect our google drive folder to google colabs.

**Comment by ricklamers** [comment]
This will be enabled by this upcoming feature: https://github.com/orchest/orchest/issues/958
