### ISSUE TITLE
How can i set up remote access to orchest?

### ISSUE THREAD

**Issue by glxhb** [orchest/orchest#841]
It was pretty straight forward when everything was running in docker containers, but I am not tech savvy enough to set it up with Minikube. How do I set up remote access I can connect to through a VPN?

**Comment by ricklamers** [comment]
Hi @glxhb. Could you explain a bit more about how you're running Orchest? Did you create a Virtual Machine on a cloud platform to install the `minikube` based version?

Happy you to guide you through any steps that are needed depending on your setup.

We'll also use it as an opportunity to improve our installation documentation ;)

**Comment by glxhb** [comment]
Apologies for the lack of information, was not sure how much was needed.

We are running an Ubuntu 20.04 VM on a self hosted server where we run the Minikube orchest container. The server is accessed through a self hosted VPN.

**Comment by glxhb** [comment]
Much appreciated, thank you.

**Comment by glxhb** [comment]
Works like a charm. Thank you!
