### ISSUE TITLE
Improved dev process for making `base-image` changes

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#849]
**Describe the problem this improvement solves**
Whenever you make changes to the `base-images`, e.g. `base-kernel-py`, then testing the changes is rather hard. Because the builder pulls from DockerHub the new image won't actually be used.

In order to test your changes you need to:
1. Point the builder to the local registry
2. Push the new image to the local registry

**Describe the solution you'd like**
Not sure what a better solution would look like, but definitely removing some steps from this process. In addition, I totally forgot that the builder pulls from DockerHub and lost some time testing my changes (my guess is that others could also easily forget about this behavior).

**Comment by astrojuanlu** [comment]
In case we don't immediately tackle this issue, how would one "Point the builder to the local registry"?

**Comment by fruttasecca** [comment]
The process is quite convoluted atm:
- modify `services/orchest-api/app/app/core/image_utils.py`  by prefixing the base image name in the workflow manifest (see `def _get_*_image_build_workflow_manifest` ) with the registry ip, a search through the codebase for `registry_ip` will yield examples.
- build & redeploy the celery-worker
- port forward the `docker-registry` pod
- from now on it's the same process as pushing any image to any registry, i.e. build the desired image and push it to the registry, e.g. build with with a name like `localhost:5000/repo/image:tag` and then `docker push` it
