### ISSUE TITLE
 404 error after installation on local mode

### ISSUE THREAD

**Issue by AlvaroGarciaTEK** [orchest/orchest#851]
Hello.

I have tried to install orchest in a Linux Ubuntu (20.04) virtualization.
I have followed the instructions as explained in https://docs.orchest.io/en/stable/getting_started/installation.html, with the difference that I hace used docker as the driver for minikube

`minikube start --cpus=4 --driver=docker`

The installation seems to be OK, and no error message has been diplayed.

But when accesing **localorchest.io**  a 404 not found message is returned from nginx. The /etc/host file has been updated and the adddress is resolved, but no page is found (or is not propertly redirected)

Going into the minikube dashboard the services seem to be running as shown in the next picture.
![image](https://user-images.githubusercontent.com/102748720/161088973-10967d8e-ecb9-4012-86fd-1baee2ac732e.png)

JuanLuis has suggested using `minikube addons enable ingres` to try to solve the issue, but it doesn't seem to work. 
I have noticed that the Ingresses section from the minikube dashboard are not resolved
![image (1)](https://user-images.githubusercontent.com/102748720/161088984-2405143a-0090-43c5-ade6-df8071316426.png)

Best regards,
Alvaro

**Comment by yannickperrenet** [comment]
Hi @AlvaroGarciaTEK. We are currently working on "smoothing" the installation process (e.g. #850). 

It indeed looks like ingress did not get set up for you (when I open the minikube dashboard I do see the ingress rules, as expected), however the `orchest` script should automatically have enabled the `ingress` addon for you (to verify `minikube addons list | grep ingress`). 

I will let you know the moment we think of a solution, I am not completely sure what is going here. Hang in there :wink:

**Comment by nhaghighat** [comment]
@AlvaroGarciaTEK : could you verify ingress rules in orchest namespace by running the following command:
`kubectl get ingress -n orchest`

**Comment by AlvaroGarciaTEK** [comment]
here is the ouput:

![image](https://user-images.githubusercontent.com/102748720/161259294-03faf420-66f5-43aa-9467-afa83dea838b.png)

**Comment by nhaghighat** [comment]
@AlvaroGarciaTEK : Thanks for coming back to us. I think your browser automatically adds `www` to `localorchest.io`, so in the end your browse tries to connect to `www.localorchest.io`, can you verify you are connecting to `localorchest.io`

**Comment by astrojuanlu** [comment]
This used to be a problem for me as well. It helped to manually type the `http://` part as well (i.e. `http://localorchest.io/`) or even going directly to `http://localorchest.io/projects`.

**Comment by AlvaroGarciaTEK** [comment]
I have checked that the url I'm trying to connect to is `http://localorchest.io/`. I have also tried accesing the `projects `endpoint, as well as the IP provided by the `echo $(minikube ip)` command, with similar results
![image](https://user-images.githubusercontent.com/102748720/161487680-08e10eb8-6470-44a0-8019-b4884ec955fb.png)

**Comment by nhaghighat** [comment]
@AlvaroGarciaTEK : Thanks for coming back to us, Currently it is not possible to reach orchest via IP address. in the next release this option will be available and enabled by default.

**Comment by AlvaroGarciaTEK** [comment]
@nhaghighat I have downloaded the latest version and tried it out, but the results are the same: nginx showing a 404 not found error, when accesing the (minikube ip)

I have checked the minikube dashboard and there seems to be a error/warnings in two of the services/pods.

**-orchest-api:**
![image](https://user-images.githubusercontent.com/102748720/162163097-288f263b-2a50-49fa-810b-c3d04589dce7.png)

**-orchest-webserver:**
![image](https://user-images.githubusercontent.com/102748720/162163177-af723f86-d315-41a1-ad79-0c91141f7d20.png)

**Comment by nhaghighat** [comment]
@AlvaroGarciaTEK : Could you try it in a fresh minikube cluster. (i.e deleting your cluster and re creating it)

**Comment by AlvaroGarciaTEK** [comment]
@nhaghighat I have tried but the results are the same

**Comment by yannickperrenet** [comment]
From the provided images it seems like the `orchest-api` failed to start because it couldn't reach `rabbitmq`. Are all pods running for you now? 

The startup probe of the `orchest-api` shouldn't fail that often, it could be that due to limited disk size that the `rabbitmq` container could not be pulled. Given that the first time all pods were running correctly, I doubt that this is the case. Nonetheless, could you run something like `minikube ssh -- df -h /var/lib/docker`?

**Comment by AlvaroGarciaTEK** [comment]
Yes, all the pods seem to be are running ok
![image](https://user-images.githubusercontent.com/102748720/162185451-1cb2fcc7-124f-4b87-9bd0-f79bbc59f360.png)

In response to `minikube ssh -- df -h /var/lib/docker`
![image](https://user-images.githubusercontent.com/102748720/162185288-02be73f6-8ec8-46a8-b9e3-34018a6a6e91.png)

**Comment by yannickperrenet** [comment]
Thank you :thinking: 

Could you add some more details regarding how you installed Orchest, in particular:
> I have tried to install orchest in a Linux Ubuntu (20.04) virtualization.

Especially around the "virtualization" you mention. I guess something might be influencing the network stack.

**Comment by AlvaroGarciaTEK** [comment]
I have a PC with windows 10 where I run Oracle VM Virtualbox. The image is:
-Ubuntu 20.04.3 LTS (64 bit)
-8 G Memory
-50G Hard Disk
-Intel® Core™ i7-8700 CPU @ 3.20GHz × 4 Processors
-Bridged connection to my host PC's Ethernet (working without problems)

The main differences with your installation steps is that since it's a virtualization i need to change the default minikube driver to docker `minikube start --cpus=4 --driver=docker`

I have also tried to use the bare-metal driver approach `minikube start --driver=none`. but the results are similar: orchest seems to be installed and all the pods seem to be running, but when trying to access to the IP from `minikube ip` I get a 404 not found error from nginx. I have also tried http://localhost/projects and even using https instead, with the same page being shown

**Comment by yannickperrenet** [comment]
I am not familiar enough with such a setup to know where it could possibly go wrong.

For windows user we recommend using [WSL 2](https://docs.docker.com/desktop/windows/wsl/) to make the environment as similar as possible to Linux ([windows installation mention in our docs](https://docs.orchest.io/en/latest/getting_started/installation.html#windows)). Would that be an option for you?

**Comment by AlvaroGarciaTEK** [comment]
I would need to check. Most of our deployments rely on linux based virtual machines. Seems a bit strange that it works on WSL but not on a Linux enviroment.  
Maybe the problem has to do with the minikube settings. Would it be possible to set up orchest **without** kubernetes? Setting up and linking the docker containers with docker-compose for example. It would hinder scalabilty and version maintenance, but would seem easiers to set up.

**Comment by yannickperrenet** [comment]
> Most of our deployments rely on linux based virtual machines.

We are running Orchest on EC2 instances which works great (so using VMs shouldn't be a problem). In general I don't see what could go wrong with your setup, but would love to learn what exactly breaks it. @ricklamers Any ideas?

> Maybe the problem has to do with the minikube settings.

I am running with `--driver=docker` as well and it works fine.

> Would it be possible to set up orchest without kubernetes? Setting up and linking the docker containers with docker-compose for example.

We used to run Orchest without Kubernetes (most up-to-date code is on https://github.com/orchest/orchest/tree/stale/pre-k8s-orchest which you could build and run, however it doesn't receive any further updates). Setting Orchest up without Kubernetes would break a number of points in the application, so using `docker-compose` instead wouldn't work. For example, we spawn a lot of containers/pods dynamically at runtime.

**Comment by ricklamers** [comment]
@AlvaroGarciaTEK your proposed setup should work just fine. What I suspect is what is potentially at play a deployment of the version of Orchest that doesn't support not specifying a FQDN. We recently released the version of Orchest that doesn't require specifying one making it easier to access Orchest by just going to the `minikube ip`.

If you try a clean installation you shouldn't see the issue you're describing. If you still get the same problem please do let us know, and we'll do everything we can to reproduce the problem.

**Comment by AlvaroGarciaTEK** [comment]
The last messages were done with the latest orchest version [v2022.04.0].

I ended up trying to install it in another virtual machine, and seems to be working on this one. Well, at least it shows the web page and allows to import example projects. Now it seems to have problems building the enviroments (both Python and R), but that is another different issue.

It seems that the 404 problem is not a bug but something to do with the previous virtual machine and can be closed.  
Thanks to all.

**Comment by yannickperrenet** [comment]
> Now it seems to have problems building the enviroments (both Python and R), but that is another different issue.

This might very well be disk related, so better to be on the safe side and create a VM with 100G.

> It seems that the 404 problem is not a bug but something to do with the previous virtual machine and can be closed.
Thanks to all.

Happy we got it resolved! Thanks again for your patience and let us know when we can be helpful again in the future :smile:
