### ISSUE TITLE
Create a job directly from the pipeline editor

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#852]
**Describe the feature you'd love to have in Orchest**
Create a job directly from the pipeline editor

**Is your feature request related to a problem? Please describe.**
It can be difficult for new users to find out how to create a job from an existing pipeline. Furthermore, the current steps can feel a bit cumbersome. A direct "create job from pipeline" button in the pipeline editor itself could streamline this common flow.

**Comment by fruttasecca** [comment]
With release [v2022.09.2](https://github.com/orchest/orchest/releases/tag/v2022.09.2) we can consider this closed.
