### ISSUE TITLE
Orchest API

### ISSUE THREAD

**Issue by glxhb** [orchest/orchest#865]
We often have multiple jobs and runs queued up in Orchest, and the process of checking the status of the jobs, or checking the status of the runs for a particular job deep within the run-pages can become tiresome. Having a basic API for retrieving a status of current and queued processes would be much appreciated so we can create a simple dashboard page to get a quick overview of the current progress and any potentially failed runs.

**Comment by yannickperrenet** [comment]
Thank you for your feature request! We have been tracking ideas around creating an public API for Orchest in #201, but I understand the naming confusing. So let's keep this issue open as well.

We are currently working on a few other tasks before picking up #120, after which creating a public API is a great candidate :100:

**Comment by yannickperrenet** [comment]
Given the name change of the aforementioned issue #201 to better reflect what it will solve, this issue can now be closed :+1:
