### ISSUE TITLE
K8s installation into pre-existing namespace?

### ISSUE THREAD

**Issue by HWiese1980** [orchest/orchest#866]
I'd like to be able to install Orchest into an existing K8s cluster and an already existing namespace. We use OpenShift and have a pre-defined OpenShift project -> K8s namespace which I'd like to deploy and run Orchest in.

I think the current limitation to Minikube and a fixed K8s namespace is clunky and makes things more complicated than necessary. It helps to install Orchest locally (on Mac and Linux; Windows not so much). However, it does not help to set up Orchest in a quasi-productive environment.

**Comment by ricklamers** [comment]
@HWiese1980 you’re absolutely right. You caught us early. We’re in the process of wrapping up our operator that will allow for more flexible/idiomatic deployments. I’ll make a note of making it possible to define the namespace you want to deploy in.

@nhaghighat please make note ✌🏻

**Comment by nhaghighat** [comment]
@HWiese1980 : Thanks for pointing this out. As @ricklamers mentioned we are in the process of developing orchest controller (operator), which manages `OrchestCluster` CRD. `OrchestCluster` CRD will be a namespaced resource and operator will install orchest in the namespace of the `OrchestCluster` CRD.

**Comment by mysticaltech** [comment]
Glad to hear about the operator. That is the ideal way of managing/installing such a multiple-moving-parts system.

**Comment by HWiese1980** [comment]
Oh yeah, that sounds awesome, looking forward to it! I've managed to run Orchest in a local minikube cluster on a MacBook so far, however I've had some issues with it in minikube on Windows and in an OpenShift namespace.

**Comment by yannickperrenet** [comment]
I'd like to give an update when it comes to installing Orchest in a custom namespace. 

With #966 it becomes possible to install Orchest in a custom namespace but only on a clean cluster (so nothing else is installed on it), installation can be done with:
```bash
pip install orchest-cli
orchest install --namespace=mynamespace
```
where the namespace will default to `orchest` if not specified.

To make it possible to install Orchest in a custom namespace on an existing cluster we need to prevent collisions between third-party software that we install on the cluster (e.g. Argo) and the software already installed on the cluster, or we need a way to deal with those collisions. Essentially, if Argo is already installed then it has created cluster-level resources which we would (in the current state of things) try to create as well. The next question to be answered is "who manages Argo now?"

Not sure exactly what will be the timeline on this, but we are working on it ;)

@nhaghighat Please feel free to correct me if I missed anything or didn't explain it properly.
