### ISSUE TITLE
Allow deletion of project from project settings

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#876]
**Describe the problem this improvement solves**
It's a bit annoying to have to search through a long list of projects to delete it.

**Describe the solution you'd like**
Allow deletion of project from project settings

**Screenshots**
Somewhere on this page:

![image](https://user-images.githubusercontent.com/1309307/164003568-8c696112-8e0b-4eba-96eb-89d443170157.png)

**Comment by yannickperrenet** [comment]
Added in #1060.
