### ISSUE TITLE
How to install orchest on a non minikube cluster?

### ISSUE THREAD

**Issue by glxhb** [orchest/orchest#885]
We have an existing kubernetes cluster where we want to deploy orchest to. Somehow this task ended up in my hands, but I am by no means a kubernetes guru. We are running a single node microk8s on an ubuntu 20.04 server.
Running the "make orchest" from the deploys directory gets stuck at "Release "orchest-resources" does not exist. Installing it now."

I am not entirely sure what I am missing, but I suspect its something quite simple.

**Comment by ricklamers** [comment]
We're working on a custom operator to make this process seamless. The expected ETA is sometime next week if we don't hit any more road bumps. Thanks for letting us know about this!

Here's the branch on which we're developing: https://github.com/orchest/orchest/tree/feat/orchest-k8s-controller

@nhaghighat and @yannickperrenet can give you more details!

**Comment by ricklamers** [comment]
Pro-tip, if you're new to `k8s` and haven't checked out `k9s` yet, would highly recommend it. It makes inspecting the cluster a breeze through its wicked TUI.

https://github.com/derailed/k9s

**Comment by nhaghighat** [comment]
@glxhb : Thanks for reaching out to us, I suspect it might be related to the mismatch between the minikube storage classes and mikrok8s storage classes, could you run the following command and return the response.
`kubectl get sc`

**Comment by glxhb** [comment]
<img width="839" alt="Screenshot 2022-04-22 at 12 02 13" src="https://user-images.githubusercontent.com/68229766/164684760-1f228e66-59f5-4bc5-ac37-034d47d9fc4f.png">

**Comment by glxhb** [comment]
Looks like its getting stuck again running `REGISTRY_STORAGE_CLASS=nfs-csi make orchest`

`Release "registry-resources" does not exist. Installing it now.
NAME: registry-resources
LAST DEPLOYED: Fri Apr 22 10:13:27 2022
NAMESPACE: orchest
STATUS: deployed
REVISION: 1
TEST SUITE: None
helm upgrade --install registry --namespace orchest   --create-namespace --atomic --timeout 1800s --set tlsSecretName=registry-tls-secret --set fullnameOverride=docker-registry --set service.port=443 --set persistence.enabled=true --set persistence.size=999Ti --set persistence.storageClass=nfs-csi thirdparty/docker-registry
Release "registry" does not exist. Installing it now.
NAME: registry
LAST DEPLOYED: Fri Apr 22 10:13:28 2022
NAMESPACE: orchest
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace orchest -l "app=docker-registry,release=registry" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl -n orchest port-forward $POD_NAME 8080:5000
helm upgrade --install orchest-resources --namespace orchest   --create-namespace --atomic --timeout 1800s --set cluster-resources.enabled=true --set cluster-resources.orchest.filesystem.storageClass=standard   --set cluster-resources.orchest.enabled=true helm
Release "orchest-resources" does not exist. Installing it now.`

<img width="825" alt="Screenshot 2022-04-22 at 12 30 58" src="https://user-images.githubusercontent.com/68229766/164695625-20949e6a-d6a0-47e2-98e1-611bacc7f245.png">

**Comment by nhaghighat** [comment]
@glxhb : Yes, I also tried it myself. Unfortunately installing orchest on non minikube clusters, needs a lot of manual changes in the code. even after this, you need to install ingress controller. So I suggest if that's possible for you, wait for our next release which contains orchest kubernetes operator and it will help you install orchest on any k8s cluster seamless.

**Comment by mysticaltech** [comment]
@ricklamers So much waiting for the operator! My k3s cluster is patiently waiting to run Orchest! :)

**Comment by vemonet** [comment]
If that can motivate the Orchest team working on the Kubernetes integration... Our OKD (open source version of OpenShift, the Kubernetes distribution by RedHat) cluster is also patiently waiting to run Orchest 🙂

We would be also ready to help with improving the Operator to support requirements related to OKD if the code of the operator is easily accessible and testable

**Comment by yannickperrenet** [comment]
Quick update :fire: 

We hope to be releasing our Kubernetes Operator later this week! This is a big step towards the goal of drop-in installation on existing clusters. Stay tuned :)

**Comment by yannickperrenet** [comment]
Another update :smiley: 

With #916 we have released the first version of the Orchest Operator and in #966 we are about to release some improvements to make it more robust. In addition, the installation procedure of Orchest has become a two step process:
```bash
pip install orchest-cli
orchest install
```
Alternatively, you can also install Orchest using `kubectl` which will be covered in the docs (quick [sneakpeek](https://orchest--966.org.readthedocs.build/en/966/getting_started/installation.html#install-orchest-via-kubectl)).

Note that this only covers the most basic installation and has not been extensively tested on clusters other than minikube yet.

**Comment by yannickperrenet** [comment]
Orchest can now (as of release `v2022.07.2`) also run on clusters using `containerd` (added in #1048) :fire: 

For EKS, GKE, MicroK8s and minikube we have added installation instructions to our docs, find them [here](https://docs.orchest.io/en/latest/getting_started/installation.html#install-orchest).

As time progresses we will be adding installation instructions for other Kubernetes distributions as well.
