### ISSUE TITLE
Firefox client HTTP requests failing when Docker actions are performed internally

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#9]
A more detailed report about the behaviour can be found at https://github.com/docker/for-linux/issues/1034

In short: whenever a Docker operation (i.e. start or shutting down a container) occurs the ongoing HTTP requests in Firefox fail (tested on Linux).

We'll await Docker's response to this issue as we think it's not something we can directly address ourselves as it seems a more generic Docker + Linux bug.

**Comment by fruttasecca** [comment]
Same issue happens on Chrome (Version 86.0.4240.75 (Official Build) (64-bit)), Ubuntu 20.04.1 LTS.
