### ISSUE TITLE
Switching pipelines does not always show corresponding files

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#937]
**Describe the bug**
I'm observing that, when switching pipelines inside the pipeline editor, the corresponding files are not always shown, and a refresh is needed.

**Expected behavior**
Every time I switch pipelines, the corresponding files are shown.

**To Reproduce**

1. Import "quickstart" project and open the pipeline editor
2. Create a new pipeline
3. Switch to it and observe that no files are shown ✔️ 
4. Switch back to the original pipeline and observe that still no files are shown :x:
5. Refresh (or click the "pipelines" menu button again) and see the original files back ✔️ 
6. Switch to the empty pipeline and observe that the other files are still there :x:
7. Refresh (or click the "pipelines" menu button again) and see no files ✔️ 

**Screenshots**

https://user-images.githubusercontent.com/316517/167577112-43fbb399-2621-4691-97e2-d71e29c77cc5.mp4

**Environment**

- OS (e.g. macOS): Linux Mint
- Browser (e.g. Chrome): Firefox
- Orchest's version (in the settings page): v2022.05.2

**Comment by iannbing** [comment]
I think this issue has been fixed in #949 and will be included in the next release (v2022.05.4). Feel free to reopen if the issue still persists.
