### ISSUE TITLE
Document and clarify current JupyterLab terminal behavior

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#938]
_**Edit**: Repurposing this issue to document & clarify current behavior, while keeping #611 for the requested new functionality. See discussion below._

**Describe the feature you'd love to have in Orchest**
It would be nice to make the terminal behave like it is running inside the Orchest environment, with all its dependencies.

**Is your feature request related to a problem? Please describe.**
Some tasks need to be run from the command line using dependencies installed in the environment. Examples include:

- Management commands of meltano, dbt, and more
- Quick experiments running Python files from the command line to observe outputs
- Application of linters (black, isort etc)

However, at the moment when opening a Terminal, the user gets dropped to an environment that does not contain any of the dependencies installed in the environment, which live in Docker containers spawned by Jupyter Enterprise Gateway. This confuses users that are used to have a terminal sitting next to their files with access to the same Python virtual environment.

In some sense, the current setup is more similar to a remote development setting, where the Python runtime lives inside a Docker container, but with the limitation that users can't connect to such runtime from the terminal.

The only workaround is to use either a Jupyter notebook or a Jupyter console (both attached to a kernel), but there are some rough edges:

- Terminal commands need to be prefixed by an exclamation mark `!`
- Commands with interactive input block the kernel without possibility of typing such input
- Limited autocomplete support

**Additional context**
Example reaction from a user:

![image](https://user-images.githubusercontent.com/316517/167600397-d8868858-5d1c-4940-be15-1213abec2786.png)

**Comment by lalligagger** [comment]
This is such a good explanation I'd recommend keeping open if there's a label for it. 😅 Thanks!

**Comment by astrojuanlu** [comment]
To keep things tidy, let's keep #611 for "implementing terminal access to environments", and repurpose this issue to "document/clarify current terminal behavior".
