### ISSUE TITLE
Delay in completion status relative to actual execution of pipeline steps

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#945]
**Describe the problem this improvement solves**
Delay in completion status wrt actual execution. E.g. in the logs it's clear the final code of the step has already been executed but in the pipeline editor the step keeps saying "Running (10s)" for, what it seems like, exactly 10s. Are we polling too infrequently?

**Describe the solution you'd like**
Create tighter updating logic to decrease latency/increase accuracy.

**Comment by yannickperrenet** [comment]
> Are we polling too infrequently?

I think this is the case, I experience the seconds increase in multiples of 2, e.g.: "Running (2s)" -> "Running (4s)" --> "Running (6s)" -> ...
